//
// ApiError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiError: Codable, JSONEncodable, Hashable {

    /** Stable kebab-case identifier for the error. */
    public var code: String
    /** Human readable summary of what went wrong. */
    public var message: String
    /** Optional machine readable context for the error. */
    public var details: [String: AnyCodable]?
    /** Correlation identifier attached to the request/response. */
    public var requestId: UUID

    public init(code: String, message: String, details: [String: AnyCodable]? = nil, requestId: UUID) {
        self.code = code
        self.message = message
        self.details = details
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
        case requestId = "request_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encode(requestId, forKey: .requestId)
    }
}

