//
// PaymentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentResponse: Codable, JSONEncodable, Hashable {

    public static let magpieMdrRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/")
    /** Unique identifier for the payment record. */
    public var id: String
    /** Associated QRPh request identifier. */
    public var qrphId: String
    public var status: String?
    public var amount: Int?
    public var magpieMdr: String?
    public var magpieFee: Int?
    public var merchantNetAmount: Int?
    public var paymentSource: String?
    public var paidAt: String?
    /** ISO timestamp when the payment record was created. */
    public var createdAt: String
    /** ISO timestamp when the payment record was last updated. */
    public var updatedAt: String
    /** Whether the payment was processed in live mode. */
    public var livemode: Bool

    public init(id: String, qrphId: String, status: String? = nil, amount: Int? = nil, magpieMdr: String? = nil, magpieFee: Int? = nil, merchantNetAmount: Int? = nil, paymentSource: String? = nil, paidAt: String? = nil, createdAt: String, updatedAt: String, livemode: Bool) {
        self.id = id
        self.qrphId = qrphId
        self.status = status
        self.amount = amount
        self.magpieMdr = magpieMdr
        self.magpieFee = magpieFee
        self.merchantNetAmount = merchantNetAmount
        self.paymentSource = paymentSource
        self.paidAt = paidAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.livemode = livemode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case qrphId = "qrph_id"
        case status
        case amount
        case magpieMdr = "magpie_mdr"
        case magpieFee = "magpie_fee"
        case merchantNetAmount = "merchant_net_amount"
        case paymentSource = "payment_source"
        case paidAt = "paid_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case livemode
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(qrphId, forKey: .qrphId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(magpieMdr, forKey: .magpieMdr)
        try container.encodeIfPresent(magpieFee, forKey: .magpieFee)
        try container.encodeIfPresent(merchantNetAmount, forKey: .merchantNetAmount)
        try container.encodeIfPresent(paymentSource, forKey: .paymentSource)
        try container.encodeIfPresent(paidAt, forKey: .paidAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(livemode, forKey: .livemode)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        qrphId = try container.decode(String.self, forKey: .qrphId)
        status = try container.decodeIfPresent(String.self, forKey: .status)
        amount = try container.decodeIfPresent(Int.self, forKey: .amount)
        magpieMdr = try container.decodeIfPresent(String.self, forKey: .magpieMdr)
        magpieFee = try container.decodeIfPresent(Int.self, forKey: .magpieFee)
        merchantNetAmount = try container.decodeIfPresent(Int.self, forKey: .merchantNetAmount)
        paymentSource = try container.decodeIfPresent(String.self, forKey: .paymentSource)
        paidAt = try container.decodeIfPresent(String.self, forKey: .paidAt)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        updatedAt = try container.decode(String.self, forKey: .updatedAt)
        livemode = try container.decode(Bool.self, forKey: .livemode)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("qrph_id")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("amount")
        nonAdditionalPropertyKeys.insert("magpie_mdr")
        nonAdditionalPropertyKeys.insert("magpie_fee")
        nonAdditionalPropertyKeys.insert("merchant_net_amount")
        nonAdditionalPropertyKeys.insert("payment_source")
        nonAdditionalPropertyKeys.insert("paid_at")
        nonAdditionalPropertyKeys.insert("created_at")
        nonAdditionalPropertyKeys.insert("updated_at")
        nonAdditionalPropertyKeys.insert("livemode")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PaymentResponse: Identifiable {}
