# coding: utf-8

# flake8: noqa
"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from magpiepay.models.api_error import ApiError
from magpiepay.models.bank_code_collection import BankCodeCollection
from magpiepay.models.bank_code_entry import BankCodeEntry
from magpiepay.models.cancel_qrph_request import CancelQRPhRequest
from magpiepay.models.canonical_create_qr_req import CanonicalCreateQRReq
from magpiepay.models.http_validation_error import HTTPValidationError
from magpiepay.models.payment_collection_response import PaymentCollectionResponse
from magpiepay.models.payment_response import PaymentResponse
from magpiepay.models.payment_single_response import PaymentSingleResponse
from magpiepay.models.payout_collection_response import PayoutCollectionResponse
from magpiepay.models.payout_create_request import PayoutCreateRequest
from magpiepay.models.payout_destination import PayoutDestination
from magpiepay.models.payout_destination_response import PayoutDestinationResponse
from magpiepay.models.payout_response import PayoutResponse
from magpiepay.models.payout_single_response import PayoutSingleResponse
from magpiepay.models.qrph_collection_response import QRPhCollectionResponse
from magpiepay.models.qrph_response import QRPhResponse
from magpiepay.models.qrph_single_response import QRPhSingleResponse
from magpiepay.models.validation_error import ValidationError
from magpiepay.models.validation_error_loc_inner import ValidationErrorLocInner

