//
// PaymentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PaymentsAPI {

    /**
     Get payment
     
     - parameter paymentId: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPaymentV1PaymentsPaymentIdGet(paymentId: String, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: PaymentSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPaymentV1PaymentsPaymentIdGetWithRequestBuilder(paymentId: paymentId, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get payment
     - GET /v1/payments/{payment_id}
     - Retrieve the current state of a QRPh payment.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter paymentId: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<PaymentSingleResponse> 
     */
    open class func getPaymentV1PaymentsPaymentIdGetWithRequestBuilder(paymentId: String, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<PaymentSingleResponse> {
        var localVariablePath = "/v1/payments/{payment_id}"
        let paymentIdPreEscape = "\(APIHelper.mapValueToPathItem(paymentId))"
        let paymentIdPostEscape = paymentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{payment_id}", with: paymentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaymentSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List payments
     
     - parameter limit: (query) Number of payments to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Cursor returned from the previous page. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPaymentsV1PaymentsGet(limit: Int? = nil, cursor: String? = nil, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: PaymentCollectionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listPaymentsV1PaymentsGetWithRequestBuilder(limit: limit, cursor: cursor, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List payments
     - GET /v1/payments/
     - Returns a paginated list of QRPh payments for the authenticated organization.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter limit: (query) Number of payments to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Cursor returned from the previous page. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<PaymentCollectionResponse> 
     */
    open class func listPaymentsV1PaymentsGetWithRequestBuilder(limit: Int? = nil, cursor: String? = nil, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<PaymentCollectionResponse> {
        let localVariablePath = "/v1/payments/"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaymentCollectionResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
