/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceId Client-provided identifier used to correlate the QRPh request.
 * @param type QR type, dynamic for fixed payments or static for amount-less flows.
 * @param amount 
 * @param submerchantId 
 * @param metadata 
 */


data class CanonicalCreateQRReq (

    /* Client-provided identifier used to correlate the QRPh request. */
    @Json(name = "reference_id")
    val referenceId: kotlin.String,

    /* QR type, dynamic for fixed payments or static for amount-less flows. */
    @Json(name = "type")
    val type: CanonicalCreateQRReq.Type,

    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    @Json(name = "submerchant_id")
    val submerchantId: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * QR type, dynamic for fixed payments or static for amount-less flows.
     *
     * Values: static,`dynamic`
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "static") static("static"),
        @Json(name = "dynamic") `dynamic`("dynamic");
    }

}

