/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique identifier for the payment record.
 * @param qrphId Associated QRPh request identifier.
 * @param createdAt ISO timestamp when the payment record was created.
 * @param updatedAt ISO timestamp when the payment record was last updated.
 * @param livemode Whether the payment was processed in live mode.
 * @param status 
 * @param amount 
 * @param magpieMdr 
 * @param magpieFee 
 * @param merchantNetAmount 
 * @param paymentSource 
 * @param paidAt 
 */


data class PaymentResponse (

    /* Unique identifier for the payment record. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Associated QRPh request identifier. */
    @Json(name = "qrph_id")
    val qrphId: kotlin.String,

    /* ISO timestamp when the payment record was created. */
    @Json(name = "created_at")
    val createdAt: kotlin.String,

    /* ISO timestamp when the payment record was last updated. */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String,

    /* Whether the payment was processed in live mode. */
    @Json(name = "livemode")
    val livemode: kotlin.Boolean,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    @Json(name = "magpie_mdr")
    val magpieMdr: kotlin.String? = null,

    @Json(name = "magpie_fee")
    val magpieFee: kotlin.Int? = null,

    @Json(name = "merchant_net_amount")
    val merchantNetAmount: kotlin.Int? = null,

    @Json(name = "payment_source")
    val paymentSource: kotlin.String? = null,

    @Json(name = "paid_at")
    val paidAt: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

