/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PayoutDestinationResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique payout identifier.
 * @param referenceId Client-provided reference tying to the payout request.
 * @param channel Payment channel (instapay/pesonet).
 * @param amount Amount in centavos.
 * @param sourceAccountId Org bank account used as source.
 * @param destination Destination bank account data.
 * @param status Current status of the payout.
 * @param createdAt ISO timestamp when payout was created.
 * @param updatedAt ISO timestamp when the payout was last modified.
 * @param livemode True when the payout was created in live mode.
 * @param magpieFee 
 * @param purpose 
 * @param provider 
 * @param providerRef Provider-specific reference data.
 * @param providerMessage 
 * @param metadata Merchant-defined metadata.
 * @param postedAt 
 * @param completedAt 
 * @param failedAt 
 * @param failureCode 
 * @param failureMessage 
 */


data class PayoutResponse (

    /* Unique payout identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Client-provided reference tying to the payout request. */
    @Json(name = "reference_id")
    val referenceId: kotlin.String,

    /* Payment channel (instapay/pesonet). */
    @Json(name = "channel")
    val channel: kotlin.String,

    /* Amount in centavos. */
    @Json(name = "amount")
    val amount: kotlin.Int,

    /* Org bank account used as source. */
    @Json(name = "source_account_id")
    val sourceAccountId: kotlin.String,

    /* Destination bank account data. */
    @Json(name = "destination")
    val destination: PayoutDestinationResponse,

    /* Current status of the payout. */
    @Json(name = "status")
    val status: kotlin.String,

    /* ISO timestamp when payout was created. */
    @Json(name = "created_at")
    val createdAt: kotlin.String,

    /* ISO timestamp when the payout was last modified. */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String,

    /* True when the payout was created in live mode. */
    @Json(name = "livemode")
    val livemode: kotlin.Boolean,

    @Json(name = "magpie_fee")
    val magpieFee: kotlin.Int? = null,

    @Json(name = "purpose")
    val purpose: kotlin.String? = null,

    @Json(name = "provider")
    val provider: kotlin.String? = null,

    /* Provider-specific reference data. */
    @Json(name = "provider_ref")
    val providerRef: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "provider_message")
    val providerMessage: kotlin.String? = null,

    /* Merchant-defined metadata. */
    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "posted_at")
    val postedAt: kotlin.String? = null,

    @Json(name = "completed_at")
    val completedAt: kotlin.String? = null,

    @Json(name = "failed_at")
    val failedAt: kotlin.String? = null,

    @Json(name = "failure_code")
    val failureCode: kotlin.String? = null,

    @Json(name = "failure_message")
    val failureMessage: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

