/* tslint:disable */
/* eslint-disable */
/**
 * Magpie API Documentation
 * Magpie API for QRPh and Disbursement services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiError {
    /**
     * Stable kebab-case identifier for the error.
     */
    'code': string;
    /**
     * Human readable summary of what went wrong.
     */
    'message': string;
    /**
     * Optional machine readable context for the error.
     */
    'details'?: { [key: string]: any; };
    /**
     * Correlation identifier attached to the request/response.
     */
    'request_id': string;
}
export interface BankCodeCollection {
    'data': Array<BankCodeEntry>;
}
export interface BankCodeEntry {
    'code': string;
    'name'?: string | null;
}
export interface CancelQRPhRequest {
    'cancellation_reason'?: string | null;
}
export interface CanonicalCreateQRReq {
    /**
     * Client-provided identifier used to correlate the QRPh request.
     */
    'reference_id': string;
    /**
     * QR type, dynamic for fixed payments or static for amount-less flows.
     */
    'type': CanonicalCreateQRReqTypeEnum;
    'amount'?: number | null;
    'submerchant_id'?: string | null;
    'metadata'?: { [key: string]: any; } | null;
}

export const CanonicalCreateQRReqTypeEnum = {
    Static: 'static',
    Dynamic: 'dynamic'
} as const;

export type CanonicalCreateQRReqTypeEnum = typeof CanonicalCreateQRReqTypeEnum[keyof typeof CanonicalCreateQRReqTypeEnum];

export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface PaymentCollectionResponse {
    'data': Array<PaymentResponse>;
    'limit': number;
    'next_cursor': string;
}
export interface PaymentResponse {
    [key: string]: any;

    /**
     * Unique identifier for the payment record.
     */
    'id': string;
    /**
     * Associated QRPh request identifier.
     */
    'qrph_id': string;
    'status'?: string | null;
    'amount'?: number | null;
    'magpie_mdr'?: string | null;
    'magpie_fee'?: number | null;
    'merchant_net_amount'?: number | null;
    'payment_source'?: string | null;
    'paid_at'?: string | null;
    /**
     * ISO timestamp when the payment record was created.
     */
    'created_at': string;
    /**
     * ISO timestamp when the payment record was last updated.
     */
    'updated_at': string;
    /**
     * Whether the payment was processed in live mode.
     */
    'livemode': boolean;
}
export interface PaymentSingleResponse {
    'data': PaymentResponse;
}
export interface PayoutCollectionResponse {
    'data': Array<PayoutResponse>;
    'limit': number;
    'next_cursor': string;
}
export interface PayoutCreateRequest {
    /**
     * Client-provided reference for the payout.
     */
    'reference_id': string;
    /**
     * Channel to use for the payout.
     */
    'channel': PayoutCreateRequestChannelEnum;
    /**
     * Amount in centavos.
     */
    'amount': number;
    /**
     * Org bank account ID to debit.
     */
    'source_account_id': string;
    /**
     * Destination account details.
     */
    'destination': PayoutDestination;
    'purpose'?: string | null;
    'metadata'?: { [key: string]: any; } | null;
}

export const PayoutCreateRequestChannelEnum = {
    Instapay: 'instapay',
    Pesonet: 'pesonet'
} as const;

export type PayoutCreateRequestChannelEnum = typeof PayoutCreateRequestChannelEnum[keyof typeof PayoutCreateRequestChannelEnum];

export interface PayoutDestination {
    'first_name'?: string | null;
    'last_name'?: string | null;
    /**
     * Bank code for the beneficiary account.
     */
    'bank_code': string;
    /**
     * Beneficiary account number.
     */
    'account_number': string;
}
export interface PayoutDestinationResponse {
    'first_name'?: string | null;
    'last_name'?: string | null;
    'bank_code'?: string | null;
    'account_number'?: string | null;
}
export interface PayoutResponse {
    [key: string]: any;

    /**
     * Unique payout identifier.
     */
    'id': string;
    /**
     * Client-provided reference tying to the payout request.
     */
    'reference_id': string;
    /**
     * Payment channel (instapay/pesonet).
     */
    'channel': string;
    /**
     * Amount in centavos.
     */
    'amount': number;
    'magpie_fee'?: number | null;
    /**
     * Org bank account used as source.
     */
    'source_account_id': string;
    /**
     * Destination bank account data.
     */
    'destination': PayoutDestinationResponse;
    'purpose'?: string | null;
    /**
     * Current status of the payout.
     */
    'status': string;
    'provider'?: string | null;
    /**
     * Provider-specific reference data.
     */
    'provider_ref'?: { [key: string]: any; };
    'provider_message'?: string | null;
    /**
     * Merchant-defined metadata.
     */
    'metadata'?: { [key: string]: any; };
    /**
     * ISO timestamp when payout was created.
     */
    'created_at': string;
    /**
     * ISO timestamp when the payout was last modified.
     */
    'updated_at': string;
    'posted_at'?: string | null;
    'completed_at'?: string | null;
    'failed_at'?: string | null;
    'failure_code'?: string | null;
    'failure_message'?: string | null;
    /**
     * True when the payout was created in live mode.
     */
    'livemode': boolean;
}
export interface PayoutSingleResponse {
    'data': PayoutResponse;
}
export interface QRPhCollectionResponse {
    'data': Array<QRPhResponse>;
    'limit': number;
    'next_cursor': string;
}
export interface QRPhResponse {
    [key: string]: any;

    /**
     * Unique identifier for the QRPh request.
     */
    'id': string;
    /**
     * Client-provided reference for correlating the request.
     */
    'reference_id': string;
    /**
     * QR code type, either static or dynamic.
     */
    'type': QRPhResponseTypeEnum;
    'amount'?: number | null;
    'submerchant_id'?: string | null;
    /**
     * Current status of the QRPh request.
     */
    'status': QRPhResponseStatusEnum;
    'metadata'?: { [key: string]: any; } | null;
    'qrph_payload'?: string | null;
    'qrph_image'?: string | null;
    'checkout_url'?: string | null;
    'payment_id'?: string | null;
    'paid_at'?: string | null;
    'expires_at'?: string | null;
    'cancelled_at'?: string | null;
    'cancellation_reason'?: string | null;
    /**
     * ISO timestamp when the QRPh request was created.
     */
    'created_at': string;
    /**
     * ISO timestamp when the QRPh request was last updated.
     */
    'updated_at': string;
    /**
     * Indicates whether the request was created in live or test mode.
     */
    'livemode': boolean;
}

export const QRPhResponseTypeEnum = {
    Static: 'static',
    Dynamic: 'dynamic'
} as const;

export type QRPhResponseTypeEnum = typeof QRPhResponseTypeEnum[keyof typeof QRPhResponseTypeEnum];
export const QRPhResponseStatusEnum = {
    Active: 'active',
    Paid: 'paid',
    Cancelled: 'cancelled',
    Expired: 'expired'
} as const;

export type QRPhResponseStatusEnum = typeof QRPhResponseStatusEnum[keyof typeof QRPhResponseStatusEnum];

export interface QRPhSingleResponse {
    'data': QRPhResponse;
}
export interface ValidationError {
    'loc': Array<ValidationErrorLocInner>;
    'msg': string;
    'type': string;
}
export interface ValidationErrorLocInner {
}

/**
 * PaymentsApi - axios parameter creator
 */
export const PaymentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve the current state of a QRPh payment.
         * @summary Get payment
         * @param {string} paymentId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentV1PaymentsPaymentIdGet: async (paymentId: string, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentId' is not null or undefined
            assertParamExists('getPaymentV1PaymentsPaymentIdGet', 'paymentId', paymentId)
            const localVarPath = `/v1/payments/{payment_id}`
                .replace(`{${"payment_id"}}`, encodeURIComponent(String(paymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated list of QRPh payments for the authenticated organization.
         * @summary List payments
         * @param {number} [limit] Number of payments to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPaymentsV1PaymentsGet: async (limit?: number, cursor?: string | null, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/payments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentsApi - functional programming interface
 */
export const PaymentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve the current state of a QRPh payment.
         * @summary Get payment
         * @param {string} paymentId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaymentV1PaymentsPaymentIdGet(paymentId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaymentV1PaymentsPaymentIdGet(paymentId, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.getPaymentV1PaymentsPaymentIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated list of QRPh payments for the authenticated organization.
         * @summary List payments
         * @param {number} [limit] Number of payments to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPaymentsV1PaymentsGet(limit?: number, cursor?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentCollectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPaymentsV1PaymentsGet(limit, cursor, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.listPaymentsV1PaymentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentsApi - factory interface
 */
export const PaymentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentsApiFp(configuration)
    return {
        /**
         * Retrieve the current state of a QRPh payment.
         * @summary Get payment
         * @param {string} paymentId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentV1PaymentsPaymentIdGet(paymentId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PaymentSingleResponse> {
            return localVarFp.getPaymentV1PaymentsPaymentIdGet(paymentId, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated list of QRPh payments for the authenticated organization.
         * @summary List payments
         * @param {number} [limit] Number of payments to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPaymentsV1PaymentsGet(limit?: number, cursor?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PaymentCollectionResponse> {
            return localVarFp.listPaymentsV1PaymentsGet(limit, cursor, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentsApi - object-oriented interface
 */
export class PaymentsApi extends BaseAPI {
    /**
     * Retrieve the current state of a QRPh payment.
     * @summary Get payment
     * @param {string} paymentId 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPaymentV1PaymentsPaymentIdGet(paymentId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).getPaymentV1PaymentsPaymentIdGet(paymentId, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated list of QRPh payments for the authenticated organization.
     * @summary List payments
     * @param {number} [limit] Number of payments to return (1-100).
     * @param {string | null} [cursor] Cursor returned from the previous page.
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPaymentsV1PaymentsGet(limit?: number, cursor?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).listPaymentsV1PaymentsGet(limit, cursor, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PayoutsApi - axios parameter creator
 */
export const PayoutsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Initiates a payout using a canonical payload and returns the normalized payout record.
         * @summary Create a payout
         * @param {PayoutCreateRequest} payoutCreateRequest 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayoutV1PayoutsPost: async (payoutCreateRequest: PayoutCreateRequest, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'payoutCreateRequest' is not null or undefined
            assertParamExists('createPayoutV1PayoutsPost', 'payoutCreateRequest', payoutCreateRequest)
            const localVarPath = `/v1/payouts/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(payoutCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the latest state for a payout.
         * @summary Get payout
         * @param {string} payoutId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayoutV1PayoutsPayoutIdGet: async (payoutId: string, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'payoutId' is not null or undefined
            assertParamExists('getPayoutV1PayoutsPayoutIdGet', 'payoutId', payoutId)
            const localVarPath = `/v1/payouts/{payout_id}`
                .replace(`{${"payout_id"}}`, encodeURIComponent(String(payoutId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated collection of payouts for the authenticated organization.
         * @summary List payouts
         * @param {number} [limit] Number of payouts to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [referenceId] Filter payouts by reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPayoutsV1PayoutsGet: async (limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/payouts/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (referenceId !== undefined) {
                localVarQueryParameter['reference_id'] = referenceId;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PayoutsApi - functional programming interface
 */
export const PayoutsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PayoutsApiAxiosParamCreator(configuration)
    return {
        /**
         * Initiates a payout using a canonical payload and returns the normalized payout record.
         * @summary Create a payout
         * @param {PayoutCreateRequest} payoutCreateRequest 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPayoutV1PayoutsPost(payoutCreateRequest: PayoutCreateRequest, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PayoutSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPayoutV1PayoutsPost(payoutCreateRequest, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayoutsApi.createPayoutV1PayoutsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the latest state for a payout.
         * @summary Get payout
         * @param {string} payoutId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayoutV1PayoutsPayoutIdGet(payoutId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PayoutSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayoutV1PayoutsPayoutIdGet(payoutId, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayoutsApi.getPayoutV1PayoutsPayoutIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated collection of payouts for the authenticated organization.
         * @summary List payouts
         * @param {number} [limit] Number of payouts to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [referenceId] Filter payouts by reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPayoutsV1PayoutsGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PayoutCollectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPayoutsV1PayoutsGet(limit, cursor, referenceId, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayoutsApi.listPayoutsV1PayoutsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PayoutsApi - factory interface
 */
export const PayoutsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PayoutsApiFp(configuration)
    return {
        /**
         * Initiates a payout using a canonical payload and returns the normalized payout record.
         * @summary Create a payout
         * @param {PayoutCreateRequest} payoutCreateRequest 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayoutV1PayoutsPost(payoutCreateRequest: PayoutCreateRequest, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PayoutSingleResponse> {
            return localVarFp.createPayoutV1PayoutsPost(payoutCreateRequest, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the latest state for a payout.
         * @summary Get payout
         * @param {string} payoutId 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayoutV1PayoutsPayoutIdGet(payoutId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PayoutSingleResponse> {
            return localVarFp.getPayoutV1PayoutsPayoutIdGet(payoutId, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated collection of payouts for the authenticated organization.
         * @summary List payouts
         * @param {number} [limit] Number of payouts to return (1-100).
         * @param {string | null} [cursor] Cursor returned from the previous page.
         * @param {string | null} [referenceId] Filter payouts by reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPayoutsV1PayoutsGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PayoutCollectionResponse> {
            return localVarFp.listPayoutsV1PayoutsGet(limit, cursor, referenceId, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PayoutsApi - object-oriented interface
 */
export class PayoutsApi extends BaseAPI {
    /**
     * Initiates a payout using a canonical payload and returns the normalized payout record.
     * @summary Create a payout
     * @param {PayoutCreateRequest} payoutCreateRequest 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPayoutV1PayoutsPost(payoutCreateRequest: PayoutCreateRequest, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return PayoutsApiFp(this.configuration).createPayoutV1PayoutsPost(payoutCreateRequest, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the latest state for a payout.
     * @summary Get payout
     * @param {string} payoutId 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPayoutV1PayoutsPayoutIdGet(payoutId: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return PayoutsApiFp(this.configuration).getPayoutV1PayoutsPayoutIdGet(payoutId, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated collection of payouts for the authenticated organization.
     * @summary List payouts
     * @param {number} [limit] Number of payouts to return (1-100).
     * @param {string | null} [cursor] Cursor returned from the previous page.
     * @param {string | null} [referenceId] Filter payouts by reference ID.
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPayoutsV1PayoutsGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return PayoutsApiFp(this.configuration).listPayoutsV1PayoutsGet(limit, cursor, referenceId, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QRPhRequestsApi - axios parameter creator
 */
export const QRPhRequestsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancels the specified QRPh request and returns the updated request record.
         * @summary Cancel a QRPh request
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {CancelQRPhRequest} [cancelQRPhRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelQrphV1QrphIdCancelPost: async (id: string, xAPIKey?: string | null, authorization?: string | null, cancelQRPhRequest?: CancelQRPhRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelQrphV1QrphIdCancelPost', 'id', id)
            const localVarPath = `/v1/qrph/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelQRPhRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.
         * @summary Create a QRPh request
         * @param {CanonicalCreateQRReq} canonicalCreateQRReq 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQrphV1QrphPost: async (canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'canonicalCreateQRReq' is not null or undefined
            assertParamExists('createQrphV1QrphPost', 'canonicalCreateQRReq', canonicalCreateQRReq)
            const localVarPath = `/v1/qrph/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(canonicalCreateQRReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the current QRPh request state, including checkout URLs and payment IDs.
         * @summary Get QRPh status
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQrphStatusV1QrphIdGet: async (id: string, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getQrphStatusV1QrphIdGet', 'id', id)
            const localVarPath = `/v1/qrph/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.
         * @summary List QRPh requests
         * @param {number} [limit] Number of items to return (1-100).
         * @param {string | null} [cursor] Opaque cursor returned from the previous page for pagination.
         * @param {string | null} [referenceId] Filter on a specific request reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQrphV1QrphGet: async (limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/qrph/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (referenceId !== undefined) {
                localVarQueryParameter['reference_id'] = referenceId;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QRPhRequestsApi - functional programming interface
 */
export const QRPhRequestsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QRPhRequestsApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancels the specified QRPh request and returns the updated request record.
         * @summary Cancel a QRPh request
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {CancelQRPhRequest} [cancelQRPhRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelQrphV1QrphIdCancelPost(id: string, xAPIKey?: string | null, authorization?: string | null, cancelQRPhRequest?: CancelQRPhRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QRPhSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelQrphV1QrphIdCancelPost(id, xAPIKey, authorization, cancelQRPhRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QRPhRequestsApi.cancelQrphV1QrphIdCancelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.
         * @summary Create a QRPh request
         * @param {CanonicalCreateQRReq} canonicalCreateQRReq 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQrphV1QrphPost(canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QRPhSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createQrphV1QrphPost(canonicalCreateQRReq, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QRPhRequestsApi.createQrphV1QrphPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the current QRPh request state, including checkout URLs and payment IDs.
         * @summary Get QRPh status
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQrphStatusV1QrphIdGet(id: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QRPhSingleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQrphStatusV1QrphIdGet(id, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QRPhRequestsApi.getQrphStatusV1QrphIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.
         * @summary List QRPh requests
         * @param {number} [limit] Number of items to return (1-100).
         * @param {string | null} [cursor] Opaque cursor returned from the previous page for pagination.
         * @param {string | null} [referenceId] Filter on a specific request reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQrphV1QrphGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QRPhCollectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQrphV1QrphGet(limit, cursor, referenceId, xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QRPhRequestsApi.listQrphV1QrphGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QRPhRequestsApi - factory interface
 */
export const QRPhRequestsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QRPhRequestsApiFp(configuration)
    return {
        /**
         * Cancels the specified QRPh request and returns the updated request record.
         * @summary Cancel a QRPh request
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {CancelQRPhRequest} [cancelQRPhRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelQrphV1QrphIdCancelPost(id: string, xAPIKey?: string | null, authorization?: string | null, cancelQRPhRequest?: CancelQRPhRequest, options?: RawAxiosRequestConfig): AxiosPromise<QRPhSingleResponse> {
            return localVarFp.cancelQrphV1QrphIdCancelPost(id, xAPIKey, authorization, cancelQRPhRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.
         * @summary Create a QRPh request
         * @param {CanonicalCreateQRReq} canonicalCreateQRReq 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQrphV1QrphPost(canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<QRPhSingleResponse> {
            return localVarFp.createQrphV1QrphPost(canonicalCreateQRReq, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the current QRPh request state, including checkout URLs and payment IDs.
         * @summary Get QRPh status
         * @param {string} id 
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQrphStatusV1QrphIdGet(id: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<QRPhSingleResponse> {
            return localVarFp.getQrphStatusV1QrphIdGet(id, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.
         * @summary List QRPh requests
         * @param {number} [limit] Number of items to return (1-100).
         * @param {string | null} [cursor] Opaque cursor returned from the previous page for pagination.
         * @param {string | null} [referenceId] Filter on a specific request reference ID.
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQrphV1QrphGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<QRPhCollectionResponse> {
            return localVarFp.listQrphV1QrphGet(limit, cursor, referenceId, xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QRPhRequestsApi - object-oriented interface
 */
export class QRPhRequestsApi extends BaseAPI {
    /**
     * Cancels the specified QRPh request and returns the updated request record.
     * @summary Cancel a QRPh request
     * @param {string} id 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {CancelQRPhRequest} [cancelQRPhRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelQrphV1QrphIdCancelPost(id: string, xAPIKey?: string | null, authorization?: string | null, cancelQRPhRequest?: CancelQRPhRequest, options?: RawAxiosRequestConfig) {
        return QRPhRequestsApiFp(this.configuration).cancelQrphV1QrphIdCancelPost(id, xAPIKey, authorization, cancelQRPhRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.
     * @summary Create a QRPh request
     * @param {CanonicalCreateQRReq} canonicalCreateQRReq 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createQrphV1QrphPost(canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return QRPhRequestsApiFp(this.configuration).createQrphV1QrphPost(canonicalCreateQRReq, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the current QRPh request state, including checkout URLs and payment IDs.
     * @summary Get QRPh status
     * @param {string} id 
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQrphStatusV1QrphIdGet(id: string, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return QRPhRequestsApiFp(this.configuration).getQrphStatusV1QrphIdGet(id, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.
     * @summary List QRPh requests
     * @param {number} [limit] Number of items to return (1-100).
     * @param {string | null} [cursor] Opaque cursor returned from the previous page for pagination.
     * @param {string | null} [referenceId] Filter on a specific request reference ID.
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQrphV1QrphGet(limit?: number, cursor?: string | null, referenceId?: string | null, xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return QRPhRequestsApiFp(this.configuration).listQrphV1QrphGet(limit, cursor, referenceId, xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ReferencesApi - axios parameter creator
 */
export const ReferencesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Bank Codes
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankCodesV1ReferencesBankCodesGet: async (xAPIKey?: string | null, authorization?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/references/bank_codes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReferencesApi - functional programming interface
 */
export const ReferencesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReferencesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Bank Codes
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBankCodesV1ReferencesBankCodesGet(xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BankCodeCollection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBankCodesV1ReferencesBankCodesGet(xAPIKey, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferencesApi.listBankCodesV1ReferencesBankCodesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReferencesApi - factory interface
 */
export const ReferencesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReferencesApiFp(configuration)
    return {
        /**
         * 
         * @summary List Bank Codes
         * @param {string | null} [xAPIKey] 
         * @param {string | null} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBankCodesV1ReferencesBankCodesGet(xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<BankCodeCollection> {
            return localVarFp.listBankCodesV1ReferencesBankCodesGet(xAPIKey, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReferencesApi - object-oriented interface
 */
export class ReferencesApi extends BaseAPI {
    /**
     * 
     * @summary List Bank Codes
     * @param {string | null} [xAPIKey] 
     * @param {string | null} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBankCodesV1ReferencesBankCodesGet(xAPIKey?: string | null, authorization?: string | null, options?: RawAxiosRequestConfig) {
        return ReferencesApiFp(this.configuration).listBankCodesV1ReferencesBankCodesGet(xAPIKey, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



