# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.api.qrph_requests_api import QRPhRequestsApi


class TestQRPhRequestsApi(unittest.TestCase):
    """QRPhRequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QRPhRequestsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_qrph_v1_qrph_id_cancel_post(self) -> None:
        """Test case for cancel_qrph_v1_qrph_id_cancel_post

        Cancel a QRPh request
        """
        pass

    def test_create_qrph_v1_qrph_post(self) -> None:
        """Test case for create_qrph_v1_qrph_post

        Create a QRPh request
        """
        pass

    def test_get_qrph_status_v1_qrph_id_get(self) -> None:
        """Test case for get_qrph_status_v1_qrph_id_get

        Get QRPh status
        """
        pass

    def test_list_qrph_v1_qrph_get(self) -> None:
        """Test case for list_qrph_v1_qrph_get

        List QRPh requests
        """
        pass


if __name__ == '__main__':
    unittest.main()
