# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.models.payout_create_request import PayoutCreateRequest

class TestPayoutCreateRequest(unittest.TestCase):
    """PayoutCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutCreateRequest:
        """Test PayoutCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutCreateRequest`
        """
        model = PayoutCreateRequest()
        if include_optional:
            return PayoutCreateRequest(
                reference_id = '0',
                channel = 'instapay',
                amount = 56,
                source_account_id = '0',
                destination = magpiepay.models.payout_destination.PayoutDestination(
                    first_name = '', 
                    last_name = '', 
                    bank_code = '', 
                    account_number = '', ),
                purpose = '',
                metadata = { }
            )
        else:
            return PayoutCreateRequest(
                reference_id = '0',
                channel = 'instapay',
                amount = 56,
                source_account_id = '0',
                destination = magpiepay.models.payout_destination.PayoutDestination(
                    first_name = '', 
                    last_name = '', 
                    bank_code = '', 
                    account_number = '', ),
        )
        """

    def testPayoutCreateRequest(self):
        """Test PayoutCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
