# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.models.canonical_create_qr_req import CanonicalCreateQRReq

class TestCanonicalCreateQRReq(unittest.TestCase):
    """CanonicalCreateQRReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CanonicalCreateQRReq:
        """Test CanonicalCreateQRReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CanonicalCreateQRReq`
        """
        model = CanonicalCreateQRReq()
        if include_optional:
            return CanonicalCreateQRReq(
                reference_id = '',
                type = 'static',
                amount = 56,
                submerchant_id = '',
                metadata = { }
            )
        else:
            return CanonicalCreateQRReq(
                reference_id = '',
                type = 'static',
        )
        """

    def testCanonicalCreateQRReq(self):
        """Test CanonicalCreateQRReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
