# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.api.payments_api import PaymentsApi


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment_v1_payments_payment_id_get(self) -> None:
        """Test case for get_payment_v1_payments_payment_id_get

        Get payment
        """
        pass

    def test_list_payments_v1_payments_get(self) -> None:
        """Test case for list_payments_v1_payments_get

        List payments
        """
        pass


if __name__ == '__main__':
    unittest.main()
