# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.api.payouts_api import PayoutsApi


class TestPayoutsApi(unittest.TestCase):
    """PayoutsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayoutsApi()

    def tearDown(self) -> None:
        pass

    def test_create_payout_v1_payouts_post(self) -> None:
        """Test case for create_payout_v1_payouts_post

        Create a payout
        """
        pass

    def test_get_payout_v1_payouts_payout_id_get(self) -> None:
        """Test case for get_payout_v1_payouts_payout_id_get

        Get payout
        """
        pass

    def test_list_payouts_v1_payouts_get(self) -> None:
        """Test case for list_payouts_v1_payouts_get

        List payouts
        """
        pass


if __name__ == '__main__':
    unittest.main()
