# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.api.references_api import ReferencesApi


class TestReferencesApi(unittest.TestCase):
    """ReferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferencesApi()

    def tearDown(self) -> None:
        pass

    def test_list_bank_codes_v1_references_bank_codes_get(self) -> None:
        """Test case for list_bank_codes_v1_references_bank_codes_get

        List Bank Codes
        """
        pass


if __name__ == '__main__':
    unittest.main()
