# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.models.qrph_single_response import QRPhSingleResponse

class TestQRPhSingleResponse(unittest.TestCase):
    """QRPhSingleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QRPhSingleResponse:
        """Test QRPhSingleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QRPhSingleResponse`
        """
        model = QRPhSingleResponse()
        if include_optional:
            return QRPhSingleResponse(
                data = {
                    'key' : null
                    }
            )
        else:
            return QRPhSingleResponse(
                data = {
                    'key' : null
                    },
        )
        """

    def testQRPhSingleResponse(self):
        """Test QRPhSingleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
