# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.models.payout_response import PayoutResponse

class TestPayoutResponse(unittest.TestCase):
    """PayoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutResponse:
        """Test PayoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutResponse`
        """
        model = PayoutResponse()
        if include_optional:
            return PayoutResponse(
                id = '',
                reference_id = '',
                channel = '',
                amount = 56,
                magpie_fee = 56,
                source_account_id = '',
                destination = magpiepay.models.payout_destination_response.PayoutDestinationResponse(
                    first_name = '', 
                    last_name = '', 
                    bank_code = '', 
                    account_number = '', ),
                purpose = '',
                status = '',
                provider = '',
                provider_ref = { },
                provider_message = '',
                metadata = { },
                created_at = '',
                updated_at = '',
                posted_at = '',
                completed_at = '',
                failed_at = '',
                failure_code = '',
                failure_message = '',
                livemode = True
            )
        else:
            return PayoutResponse(
                id = '',
                reference_id = '',
                channel = '',
                amount = 56,
                source_account_id = '',
                destination = magpiepay.models.payout_destination_response.PayoutDestinationResponse(
                    first_name = '', 
                    last_name = '', 
                    bank_code = '', 
                    account_number = '', ),
                status = '',
                created_at = '',
                updated_at = '',
                livemode = True,
        )
        """

    def testPayoutResponse(self):
        """Test PayoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
