# coding: utf-8

"""
    Magpie API Documentation

    Magpie API for QRPh and Disbursement services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from magpiepay.models.qrph_response import QRPhResponse

class TestQRPhResponse(unittest.TestCase):
    """QRPhResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QRPhResponse:
        """Test QRPhResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QRPhResponse`
        """
        model = QRPhResponse()
        if include_optional:
            return QRPhResponse(
                id = '',
                reference_id = '',
                type = 'static',
                amount = 56,
                submerchant_id = '',
                status = 'active',
                metadata = { },
                qrph_payload = '',
                qrph_image = '',
                checkout_url = '',
                payment_id = '',
                paid_at = '',
                expires_at = '',
                cancelled_at = '',
                cancellation_reason = '',
                created_at = '',
                updated_at = '',
                livemode = True
            )
        else:
            return QRPhResponse(
                id = '',
                reference_id = '',
                type = 'static',
                status = 'active',
                created_at = '',
                updated_at = '',
                livemode = True,
        )
        """

    def testQRPhResponse(self):
        """Test QRPhResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
