//
// PayoutsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PayoutsAPI {

    /**
     Create a payout
     
     - parameter payoutCreateRequest: (body)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPayout(payoutCreateRequest: PayoutCreateRequest, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: PayoutSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createPayoutWithRequestBuilder(payoutCreateRequest: payoutCreateRequest, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create a payout
     - POST /v1/payouts/
     - Initiates a payout using a canonical payload and returns the normalized payout record.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter payoutCreateRequest: (body)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<PayoutSingleResponse> 
     */
    open class func createPayoutWithRequestBuilder(payoutCreateRequest: PayoutCreateRequest, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<PayoutSingleResponse> {
        let localVariablePath = "/v1/payouts/"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: payoutCreateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PayoutSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get payout
     
     - parameter payoutId: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPayout(payoutId: String, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: PayoutSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPayoutWithRequestBuilder(payoutId: payoutId, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get payout
     - GET /v1/payouts/{payout_id}
     - Retrieves the latest state for a payout.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter payoutId: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<PayoutSingleResponse> 
     */
    open class func getPayoutWithRequestBuilder(payoutId: String, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<PayoutSingleResponse> {
        var localVariablePath = "/v1/payouts/{payout_id}"
        let payoutIdPreEscape = "\(APIHelper.mapValueToPathItem(payoutId))"
        let payoutIdPostEscape = payoutIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{payout_id}", with: payoutIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PayoutSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List payouts
     
     - parameter limit: (query) Number of payouts to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Cursor returned from the previous page. (optional)
     - parameter referenceId: (query) Filter payouts by reference ID. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPayouts(limit: Int? = nil, cursor: String? = nil, referenceId: String? = nil, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: PayoutCollectionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listPayoutsWithRequestBuilder(limit: limit, cursor: cursor, referenceId: referenceId, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List payouts
     - GET /v1/payouts/
     - Returns a paginated collection of payouts for the authenticated organization.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter limit: (query) Number of payouts to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Cursor returned from the previous page. (optional)
     - parameter referenceId: (query) Filter payouts by reference ID. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<PayoutCollectionResponse> 
     */
    open class func listPayoutsWithRequestBuilder(limit: Int? = nil, cursor: String? = nil, referenceId: String? = nil, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<PayoutCollectionResponse> {
        let localVariablePath = "/v1/payouts/"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "reference_id": (wrappedValue: referenceId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PayoutCollectionResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
