//
// QRPhRequestsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class QRPhRequestsAPI {

    /**
     Cancel a QRPh request
     
     - parameter id: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter cancelQRPhRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func cancelQrph(id: String, xAPIKey: String? = nil, authorization: String? = nil, cancelQRPhRequest: CancelQRPhRequest? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: QRPhSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return cancelQrphWithRequestBuilder(id: id, xAPIKey: xAPIKey, authorization: authorization, cancelQRPhRequest: cancelQRPhRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel a QRPh request
     - POST /v1/qrph/{id}/cancel
     - Cancels the specified QRPh request and returns the updated request record.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter id: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter cancelQRPhRequest: (body)  (optional)
     - returns: RequestBuilder<QRPhSingleResponse> 
     */
    open class func cancelQrphWithRequestBuilder(id: String, xAPIKey: String? = nil, authorization: String? = nil, cancelQRPhRequest: CancelQRPhRequest? = nil) -> RequestBuilder<QRPhSingleResponse> {
        var localVariablePath = "/v1/qrph/{id}/cancel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cancelQRPhRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QRPhSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a QRPh request
     
     - parameter canonicalCreateQRReq: (body)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createQrph(canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: QRPhSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createQrphWithRequestBuilder(canonicalCreateQRReq: canonicalCreateQRReq, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create a QRPh request
     - POST /v1/qrph/
     - Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter canonicalCreateQRReq: (body)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<QRPhSingleResponse> 
     */
    open class func createQrphWithRequestBuilder(canonicalCreateQRReq: CanonicalCreateQRReq, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<QRPhSingleResponse> {
        let localVariablePath = "/v1/qrph/"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: canonicalCreateQRReq)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QRPhSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get QRPh status
     
     - parameter id: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getQrph(id: String, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: QRPhSingleResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getQrphWithRequestBuilder(id: id, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get QRPh status
     - GET /v1/qrph/{id}
     - Returns the current QRPh request state, including checkout URLs and payment IDs.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter id: (path)  
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<QRPhSingleResponse> 
     */
    open class func getQrphWithRequestBuilder(id: String, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<QRPhSingleResponse> {
        var localVariablePath = "/v1/qrph/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QRPhSingleResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List QRPh requests
     
     - parameter limit: (query) Number of items to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Opaque cursor returned from the previous page for pagination. (optional)
     - parameter referenceId: (query) Filter on a specific request reference ID. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listQrph(limit: Int? = nil, cursor: String? = nil, referenceId: String? = nil, xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: QRPhCollectionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listQrphWithRequestBuilder(limit: limit, cursor: cursor, referenceId: referenceId, xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List QRPh requests
     - GET /v1/qrph/
     - Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter limit: (query) Number of items to return (1-100). (optional, default to 50)
     - parameter cursor: (query) Opaque cursor returned from the previous page for pagination. (optional)
     - parameter referenceId: (query) Filter on a specific request reference ID. (optional)
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<QRPhCollectionResponse> 
     */
    open class func listQrphWithRequestBuilder(limit: Int? = nil, cursor: String? = nil, referenceId: String? = nil, xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<QRPhCollectionResponse> {
        let localVariablePath = "/v1/qrph/"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "reference_id": (wrappedValue: referenceId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QRPhCollectionResponse>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
