//
// ReferencesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ReferencesAPI {

    /**
     List Bank Codes
     
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listBankCodes(xAPIKey: String? = nil, authorization: String? = nil, apiResponseQueue: DispatchQueue = MagpiePayAPI.apiResponseQueue, completion: @escaping ((_ data: BankCodeCollection?, _ error: Error?) -> Void)) -> RequestTask {
        return listBankCodesWithRequestBuilder(xAPIKey: xAPIKey, authorization: authorization).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List Bank Codes
     - GET /v1/references/bank_codes
     - BASIC:
       - type: http
       - name: basicAuth
     - parameter xAPIKey: (header)  (optional)
     - parameter authorization: (header)  (optional)
     - returns: RequestBuilder<BankCodeCollection> 
     */
    open class func listBankCodesWithRequestBuilder(xAPIKey: String? = nil, authorization: String? = nil) -> RequestBuilder<BankCodeCollection> {
        let localVariablePath = "/v1/references/bank_codes"
        let localVariableURLString = MagpiePayAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-API-Key": xAPIKey?.encodeToJSON(),
            "Authorization": authorization?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BankCodeCollection>.Type = MagpiePayAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
