/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.PayoutsApi
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.PayoutCollectionResponse
import org.openapitools.client.models.PayoutCreateRequest
import org.openapitools.client.models.PayoutSingleResponse

class PayoutsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayoutsApi
        //val apiInstance = PayoutsApi()

        // to test createPayoutV1PayoutsPost
        should("test createPayoutV1PayoutsPost") {
            // uncomment below to test createPayoutV1PayoutsPost
            //val payoutCreateRequest : PayoutCreateRequest = {"reference_id":"PAYOUT-123-456","channel":"instapay","amount":40000,"source_account_id":"act_01k90z02ps251323zgkd23cb0d","destination":{"first_name":"Juan","last_name":"Dela Cruz","bank_code":"bdo","account_number":"002400091125"},"purpose":"Salary payout"} // PayoutCreateRequest | 
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : PayoutSingleResponse = apiInstance.createPayoutV1PayoutsPost(payoutCreateRequest, xAPIKey, authorization)
            //result shouldBe ("TODO")
        }

        // to test getPayoutV1PayoutsPayoutIdGet
        should("test getPayoutV1PayoutsPayoutIdGet") {
            // uncomment below to test getPayoutV1PayoutsPayoutIdGet
            //val payoutId : kotlin.String = payoutId_example // kotlin.String | 
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : PayoutSingleResponse = apiInstance.getPayoutV1PayoutsPayoutIdGet(payoutId, xAPIKey, authorization)
            //result shouldBe ("TODO")
        }

        // to test listPayoutsV1PayoutsGet
        should("test listPayoutsV1PayoutsGet") {
            // uncomment below to test listPayoutsV1PayoutsGet
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of payouts to return (1-100).
            //val cursor : kotlin.String = cursor_example // kotlin.String | Cursor returned from the previous page.
            //val referenceId : kotlin.String = referenceId_example // kotlin.String | Filter payouts by reference ID.
            //val xAPIKey : kotlin.String = xAPIKey_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : PayoutCollectionResponse = apiInstance.listPayoutsV1PayoutsGet(limit, cursor, referenceId, xAPIKey, authorization)
            //result shouldBe ("TODO")
        }

    }
}
