/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// QRPhRequestsAPIService QRPhRequestsAPI service
type QRPhRequestsAPIService service

type ApiCancelQrphRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	id string
	xAPIKey *string
	authorization *string
	cancelQRPhRequest *CancelQRPhRequest
}

func (r ApiCancelQrphRequest) XAPIKey(xAPIKey string) ApiCancelQrphRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiCancelQrphRequest) Authorization(authorization string) ApiCancelQrphRequest {
	r.authorization = &authorization
	return r
}

func (r ApiCancelQrphRequest) CancelQRPhRequest(cancelQRPhRequest CancelQRPhRequest) ApiCancelQrphRequest {
	r.cancelQRPhRequest = &cancelQRPhRequest
	return r
}

func (r ApiCancelQrphRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.CancelQrphExecute(r)
}

/*
CancelQrph Cancel a QRPh request

Cancels the specified QRPh request and returns the updated request record.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiCancelQrphRequest
*/
func (a *QRPhRequestsAPIService) CancelQrph(ctx context.Context, id string) ApiCancelQrphRequest {
	return ApiCancelQrphRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) CancelQrphExecute(r ApiCancelQrphRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.CancelQrph")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/{id}/cancel"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.cancelQRPhRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateQrphRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	canonicalCreateQRReq *CanonicalCreateQRReq
	xAPIKey *string
	authorization *string
}

func (r ApiCreateQrphRequest) CanonicalCreateQRReq(canonicalCreateQRReq CanonicalCreateQRReq) ApiCreateQrphRequest {
	r.canonicalCreateQRReq = &canonicalCreateQRReq
	return r
}

func (r ApiCreateQrphRequest) XAPIKey(xAPIKey string) ApiCreateQrphRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiCreateQrphRequest) Authorization(authorization string) ApiCreateQrphRequest {
	r.authorization = &authorization
	return r
}

func (r ApiCreateQrphRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.CreateQrphExecute(r)
}

/*
CreateQrph Create a QRPh request

Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateQrphRequest
*/
func (a *QRPhRequestsAPIService) CreateQrph(ctx context.Context) ApiCreateQrphRequest {
	return ApiCreateQrphRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) CreateQrphExecute(r ApiCreateQrphRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.CreateQrph")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.canonicalCreateQRReq == nil {
		return localVarReturnValue, nil, reportError("canonicalCreateQRReq is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.canonicalCreateQRReq
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetQrphRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	id string
	xAPIKey *string
	authorization *string
}

func (r ApiGetQrphRequest) XAPIKey(xAPIKey string) ApiGetQrphRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiGetQrphRequest) Authorization(authorization string) ApiGetQrphRequest {
	r.authorization = &authorization
	return r
}

func (r ApiGetQrphRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.GetQrphExecute(r)
}

/*
GetQrph Get QRPh status

Returns the current QRPh request state, including checkout URLs and payment IDs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiGetQrphRequest
*/
func (a *QRPhRequestsAPIService) GetQrph(ctx context.Context, id string) ApiGetQrphRequest {
	return ApiGetQrphRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) GetQrphExecute(r ApiGetQrphRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.GetQrph")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListQrphRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	limit *int32
	cursor *string
	referenceId *string
	xAPIKey *string
	authorization *string
}

// Number of items to return (1-100).
func (r ApiListQrphRequest) Limit(limit int32) ApiListQrphRequest {
	r.limit = &limit
	return r
}

// Opaque cursor returned from the previous page for pagination.
func (r ApiListQrphRequest) Cursor(cursor string) ApiListQrphRequest {
	r.cursor = &cursor
	return r
}

// Filter on a specific request reference ID.
func (r ApiListQrphRequest) ReferenceId(referenceId string) ApiListQrphRequest {
	r.referenceId = &referenceId
	return r
}

func (r ApiListQrphRequest) XAPIKey(xAPIKey string) ApiListQrphRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiListQrphRequest) Authorization(authorization string) ApiListQrphRequest {
	r.authorization = &authorization
	return r
}

func (r ApiListQrphRequest) Execute() (*QRPhCollectionResponse, *http.Response, error) {
	return r.ApiService.ListQrphExecute(r)
}

/*
ListQrph List QRPh requests

Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListQrphRequest
*/
func (a *QRPhRequestsAPIService) ListQrph(ctx context.Context) ApiListQrphRequest {
	return ApiListQrphRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return QRPhCollectionResponse
func (a *QRPhRequestsAPIService) ListQrphExecute(r ApiListQrphRequest) (*QRPhCollectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhCollectionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.ListQrph")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
        var defaultValue int32 = 50
        parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
        r.limit = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.referenceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "reference_id", r.referenceId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
