/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// QRPhRequestsAPIService QRPhRequestsAPI service
type QRPhRequestsAPIService service

type ApiCancelQrphV1QrphIdCancelPostRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	id string
	xAPIKey *string
	authorization *string
	cancelQRPhRequest *CancelQRPhRequest
}

func (r ApiCancelQrphV1QrphIdCancelPostRequest) XAPIKey(xAPIKey string) ApiCancelQrphV1QrphIdCancelPostRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiCancelQrphV1QrphIdCancelPostRequest) Authorization(authorization string) ApiCancelQrphV1QrphIdCancelPostRequest {
	r.authorization = &authorization
	return r
}

func (r ApiCancelQrphV1QrphIdCancelPostRequest) CancelQRPhRequest(cancelQRPhRequest CancelQRPhRequest) ApiCancelQrphV1QrphIdCancelPostRequest {
	r.cancelQRPhRequest = &cancelQRPhRequest
	return r
}

func (r ApiCancelQrphV1QrphIdCancelPostRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.CancelQrphV1QrphIdCancelPostExecute(r)
}

/*
CancelQrphV1QrphIdCancelPost Cancel a QRPh request

Cancels the specified QRPh request and returns the updated request record.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiCancelQrphV1QrphIdCancelPostRequest
*/
func (a *QRPhRequestsAPIService) CancelQrphV1QrphIdCancelPost(ctx context.Context, id string) ApiCancelQrphV1QrphIdCancelPostRequest {
	return ApiCancelQrphV1QrphIdCancelPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) CancelQrphV1QrphIdCancelPostExecute(r ApiCancelQrphV1QrphIdCancelPostRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.CancelQrphV1QrphIdCancelPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/{id}/cancel"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.cancelQRPhRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateQrphV1QrphPostRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	canonicalCreateQRReq *CanonicalCreateQRReq
	xAPIKey *string
	authorization *string
}

func (r ApiCreateQrphV1QrphPostRequest) CanonicalCreateQRReq(canonicalCreateQRReq CanonicalCreateQRReq) ApiCreateQrphV1QrphPostRequest {
	r.canonicalCreateQRReq = &canonicalCreateQRReq
	return r
}

func (r ApiCreateQrphV1QrphPostRequest) XAPIKey(xAPIKey string) ApiCreateQrphV1QrphPostRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiCreateQrphV1QrphPostRequest) Authorization(authorization string) ApiCreateQrphV1QrphPostRequest {
	r.authorization = &authorization
	return r
}

func (r ApiCreateQrphV1QrphPostRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.CreateQrphV1QrphPostExecute(r)
}

/*
CreateQrphV1QrphPost Create a QRPh request

Creates a QRPh request from the canonical payload and returns the normalized request with the checkout URL attached.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateQrphV1QrphPostRequest
*/
func (a *QRPhRequestsAPIService) CreateQrphV1QrphPost(ctx context.Context) ApiCreateQrphV1QrphPostRequest {
	return ApiCreateQrphV1QrphPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) CreateQrphV1QrphPostExecute(r ApiCreateQrphV1QrphPostRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.CreateQrphV1QrphPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.canonicalCreateQRReq == nil {
		return localVarReturnValue, nil, reportError("canonicalCreateQRReq is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.canonicalCreateQRReq
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetQrphStatusV1QrphIdGetRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	id string
	xAPIKey *string
	authorization *string
}

func (r ApiGetQrphStatusV1QrphIdGetRequest) XAPIKey(xAPIKey string) ApiGetQrphStatusV1QrphIdGetRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiGetQrphStatusV1QrphIdGetRequest) Authorization(authorization string) ApiGetQrphStatusV1QrphIdGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiGetQrphStatusV1QrphIdGetRequest) Execute() (*QRPhSingleResponse, *http.Response, error) {
	return r.ApiService.GetQrphStatusV1QrphIdGetExecute(r)
}

/*
GetQrphStatusV1QrphIdGet Get QRPh status

Returns the current QRPh request state, including checkout URLs and payment IDs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiGetQrphStatusV1QrphIdGetRequest
*/
func (a *QRPhRequestsAPIService) GetQrphStatusV1QrphIdGet(ctx context.Context, id string) ApiGetQrphStatusV1QrphIdGetRequest {
	return ApiGetQrphStatusV1QrphIdGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return QRPhSingleResponse
func (a *QRPhRequestsAPIService) GetQrphStatusV1QrphIdGetExecute(r ApiGetQrphStatusV1QrphIdGetRequest) (*QRPhSingleResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhSingleResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.GetQrphStatusV1QrphIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListQrphV1QrphGetRequest struct {
	ctx context.Context
	ApiService *QRPhRequestsAPIService
	limit *int32
	cursor *string
	referenceId *string
	xAPIKey *string
	authorization *string
}

// Number of items to return (1-100).
func (r ApiListQrphV1QrphGetRequest) Limit(limit int32) ApiListQrphV1QrphGetRequest {
	r.limit = &limit
	return r
}

// Opaque cursor returned from the previous page for pagination.
func (r ApiListQrphV1QrphGetRequest) Cursor(cursor string) ApiListQrphV1QrphGetRequest {
	r.cursor = &cursor
	return r
}

// Filter on a specific request reference ID.
func (r ApiListQrphV1QrphGetRequest) ReferenceId(referenceId string) ApiListQrphV1QrphGetRequest {
	r.referenceId = &referenceId
	return r
}

func (r ApiListQrphV1QrphGetRequest) XAPIKey(xAPIKey string) ApiListQrphV1QrphGetRequest {
	r.xAPIKey = &xAPIKey
	return r
}

func (r ApiListQrphV1QrphGetRequest) Authorization(authorization string) ApiListQrphV1QrphGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiListQrphV1QrphGetRequest) Execute() (*QRPhCollectionResponse, *http.Response, error) {
	return r.ApiService.ListQrphV1QrphGetExecute(r)
}

/*
ListQrphV1QrphGet List QRPh requests

Returns a paginated collection of QRPh requests for the authenticated organization. Use `limit` and `cursor` for pagination and `reference_id` to locate a specific request.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListQrphV1QrphGetRequest
*/
func (a *QRPhRequestsAPIService) ListQrphV1QrphGet(ctx context.Context) ApiListQrphV1QrphGetRequest {
	return ApiListQrphV1QrphGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return QRPhCollectionResponse
func (a *QRPhRequestsAPIService) ListQrphV1QrphGetExecute(r ApiListQrphV1QrphGetRequest) (*QRPhCollectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *QRPhCollectionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "QRPhRequestsAPIService.ListQrphV1QrphGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/qrph/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
        var defaultValue int32 = 50
        parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
        r.limit = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.referenceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "reference_id", r.referenceId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xAPIKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-API-Key", r.xAPIKey, "simple", "")
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Authorization", r.authorization, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
