/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutCollectionResponse{}

// PayoutCollectionResponse struct for PayoutCollectionResponse
type PayoutCollectionResponse struct {
	Data []PayoutResponse `json:"data"`
	Limit int32 `json:"limit"`
	NextCursor string `json:"next_cursor"`
}

type _PayoutCollectionResponse PayoutCollectionResponse

// NewPayoutCollectionResponse instantiates a new PayoutCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutCollectionResponse(data []PayoutResponse, limit int32, nextCursor string) *PayoutCollectionResponse {
	this := PayoutCollectionResponse{}
	this.Data = data
	this.Limit = limit
	this.NextCursor = nextCursor
	return &this
}

// NewPayoutCollectionResponseWithDefaults instantiates a new PayoutCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutCollectionResponseWithDefaults() *PayoutCollectionResponse {
	this := PayoutCollectionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PayoutCollectionResponse) GetData() []PayoutResponse {
	if o == nil {
		var ret []PayoutResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PayoutCollectionResponse) GetDataOk() ([]PayoutResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PayoutCollectionResponse) SetData(v []PayoutResponse) {
	o.Data = v
}

// GetLimit returns the Limit field value
func (o *PayoutCollectionResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *PayoutCollectionResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *PayoutCollectionResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value
func (o *PayoutCollectionResponse) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *PayoutCollectionResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *PayoutCollectionResponse) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o PayoutCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["limit"] = o.Limit
	toSerialize["next_cursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *PayoutCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"limit",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutCollectionResponse := _PayoutCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutCollectionResponse)

	if err != nil {
		return err
	}

	*o = PayoutCollectionResponse(varPayoutCollectionResponse)

	return err
}

type NullablePayoutCollectionResponse struct {
	value *PayoutCollectionResponse
	isSet bool
}

func (v NullablePayoutCollectionResponse) Get() *PayoutCollectionResponse {
	return v.value
}

func (v *NullablePayoutCollectionResponse) Set(val *PayoutCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutCollectionResponse(val *PayoutCollectionResponse) *NullablePayoutCollectionResponse {
	return &NullablePayoutCollectionResponse{value: val, isSet: true}
}

func (v NullablePayoutCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


