/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentResponse{}

// PaymentResponse struct for PaymentResponse
type PaymentResponse struct {
	// Unique identifier for the payment record.
	Id string `json:"id"`
	// Associated QRPh request identifier.
	QrphId string `json:"qrph_id"`
	Status NullableString `json:"status,omitempty"`
	Amount NullableInt32 `json:"amount,omitempty"`
	MagpieMdr NullableString `json:"magpie_mdr,omitempty" validate:"regexp=^(?!^[-+.]*$)[+-]?0*\\\\d*\\\\.?\\\\d*$"`
	MagpieFee NullableInt32 `json:"magpie_fee,omitempty"`
	MerchantNetAmount NullableInt32 `json:"merchant_net_amount,omitempty"`
	PaymentSource NullableString `json:"payment_source,omitempty"`
	PaidAt NullableString `json:"paid_at,omitempty"`
	// ISO timestamp when the payment record was created.
	CreatedAt string `json:"created_at"`
	// ISO timestamp when the payment record was last updated.
	UpdatedAt string `json:"updated_at"`
	// Whether the payment was processed in live mode.
	Livemode bool `json:"livemode"`
	AdditionalProperties map[string]interface{}
}

type _PaymentResponse PaymentResponse

// NewPaymentResponse instantiates a new PaymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentResponse(id string, qrphId string, createdAt string, updatedAt string, livemode bool) *PaymentResponse {
	this := PaymentResponse{}
	this.Id = id
	this.QrphId = qrphId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Livemode = livemode
	return &this
}

// NewPaymentResponseWithDefaults instantiates a new PaymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentResponseWithDefaults() *PaymentResponse {
	this := PaymentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *PaymentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentResponse) SetId(v string) {
	o.Id = v
}

// GetQrphId returns the QrphId field value
func (o *PaymentResponse) GetQrphId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QrphId
}

// GetQrphIdOk returns a tuple with the QrphId field value
// and a boolean to check if the value has been set.
func (o *PaymentResponse) GetQrphIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QrphId, true
}

// SetQrphId sets field value
func (o *PaymentResponse) SetQrphId(v string) {
	o.QrphId = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentResponse) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *PaymentResponse) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *PaymentResponse) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *PaymentResponse) UnsetStatus() {
	o.Status.Unset()
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetAmount() int32 {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret int32
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *PaymentResponse) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableInt32 and assigns it to the Amount field.
func (o *PaymentResponse) SetAmount(v int32) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *PaymentResponse) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *PaymentResponse) UnsetAmount() {
	o.Amount.Unset()
}

// GetMagpieMdr returns the MagpieMdr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetMagpieMdr() string {
	if o == nil || IsNil(o.MagpieMdr.Get()) {
		var ret string
		return ret
	}
	return *o.MagpieMdr.Get()
}

// GetMagpieMdrOk returns a tuple with the MagpieMdr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetMagpieMdrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MagpieMdr.Get(), o.MagpieMdr.IsSet()
}

// HasMagpieMdr returns a boolean if a field has been set.
func (o *PaymentResponse) HasMagpieMdr() bool {
	if o != nil && o.MagpieMdr.IsSet() {
		return true
	}

	return false
}

// SetMagpieMdr gets a reference to the given NullableString and assigns it to the MagpieMdr field.
func (o *PaymentResponse) SetMagpieMdr(v string) {
	o.MagpieMdr.Set(&v)
}
// SetMagpieMdrNil sets the value for MagpieMdr to be an explicit nil
func (o *PaymentResponse) SetMagpieMdrNil() {
	o.MagpieMdr.Set(nil)
}

// UnsetMagpieMdr ensures that no value is present for MagpieMdr, not even an explicit nil
func (o *PaymentResponse) UnsetMagpieMdr() {
	o.MagpieMdr.Unset()
}

// GetMagpieFee returns the MagpieFee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetMagpieFee() int32 {
	if o == nil || IsNil(o.MagpieFee.Get()) {
		var ret int32
		return ret
	}
	return *o.MagpieFee.Get()
}

// GetMagpieFeeOk returns a tuple with the MagpieFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetMagpieFeeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MagpieFee.Get(), o.MagpieFee.IsSet()
}

// HasMagpieFee returns a boolean if a field has been set.
func (o *PaymentResponse) HasMagpieFee() bool {
	if o != nil && o.MagpieFee.IsSet() {
		return true
	}

	return false
}

// SetMagpieFee gets a reference to the given NullableInt32 and assigns it to the MagpieFee field.
func (o *PaymentResponse) SetMagpieFee(v int32) {
	o.MagpieFee.Set(&v)
}
// SetMagpieFeeNil sets the value for MagpieFee to be an explicit nil
func (o *PaymentResponse) SetMagpieFeeNil() {
	o.MagpieFee.Set(nil)
}

// UnsetMagpieFee ensures that no value is present for MagpieFee, not even an explicit nil
func (o *PaymentResponse) UnsetMagpieFee() {
	o.MagpieFee.Unset()
}

// GetMerchantNetAmount returns the MerchantNetAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetMerchantNetAmount() int32 {
	if o == nil || IsNil(o.MerchantNetAmount.Get()) {
		var ret int32
		return ret
	}
	return *o.MerchantNetAmount.Get()
}

// GetMerchantNetAmountOk returns a tuple with the MerchantNetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetMerchantNetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantNetAmount.Get(), o.MerchantNetAmount.IsSet()
}

// HasMerchantNetAmount returns a boolean if a field has been set.
func (o *PaymentResponse) HasMerchantNetAmount() bool {
	if o != nil && o.MerchantNetAmount.IsSet() {
		return true
	}

	return false
}

// SetMerchantNetAmount gets a reference to the given NullableInt32 and assigns it to the MerchantNetAmount field.
func (o *PaymentResponse) SetMerchantNetAmount(v int32) {
	o.MerchantNetAmount.Set(&v)
}
// SetMerchantNetAmountNil sets the value for MerchantNetAmount to be an explicit nil
func (o *PaymentResponse) SetMerchantNetAmountNil() {
	o.MerchantNetAmount.Set(nil)
}

// UnsetMerchantNetAmount ensures that no value is present for MerchantNetAmount, not even an explicit nil
func (o *PaymentResponse) UnsetMerchantNetAmount() {
	o.MerchantNetAmount.Unset()
}

// GetPaymentSource returns the PaymentSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetPaymentSource() string {
	if o == nil || IsNil(o.PaymentSource.Get()) {
		var ret string
		return ret
	}
	return *o.PaymentSource.Get()
}

// GetPaymentSourceOk returns a tuple with the PaymentSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetPaymentSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentSource.Get(), o.PaymentSource.IsSet()
}

// HasPaymentSource returns a boolean if a field has been set.
func (o *PaymentResponse) HasPaymentSource() bool {
	if o != nil && o.PaymentSource.IsSet() {
		return true
	}

	return false
}

// SetPaymentSource gets a reference to the given NullableString and assigns it to the PaymentSource field.
func (o *PaymentResponse) SetPaymentSource(v string) {
	o.PaymentSource.Set(&v)
}
// SetPaymentSourceNil sets the value for PaymentSource to be an explicit nil
func (o *PaymentResponse) SetPaymentSourceNil() {
	o.PaymentSource.Set(nil)
}

// UnsetPaymentSource ensures that no value is present for PaymentSource, not even an explicit nil
func (o *PaymentResponse) UnsetPaymentSource() {
	o.PaymentSource.Unset()
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentResponse) GetPaidAt() string {
	if o == nil || IsNil(o.PaidAt.Get()) {
		var ret string
		return ret
	}
	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentResponse) GetPaidAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// HasPaidAt returns a boolean if a field has been set.
func (o *PaymentResponse) HasPaidAt() bool {
	if o != nil && o.PaidAt.IsSet() {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given NullableString and assigns it to the PaidAt field.
func (o *PaymentResponse) SetPaidAt(v string) {
	o.PaidAt.Set(&v)
}
// SetPaidAtNil sets the value for PaidAt to be an explicit nil
func (o *PaymentResponse) SetPaidAtNil() {
	o.PaidAt.Set(nil)
}

// UnsetPaidAt ensures that no value is present for PaidAt, not even an explicit nil
func (o *PaymentResponse) UnsetPaidAt() {
	o.PaidAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *PaymentResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PaymentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PaymentResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PaymentResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PaymentResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PaymentResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetLivemode returns the Livemode field value
func (o *PaymentResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *PaymentResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *PaymentResponse) SetLivemode(v bool) {
	o.Livemode = v
}

func (o PaymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["qrph_id"] = o.QrphId
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if o.MagpieMdr.IsSet() {
		toSerialize["magpie_mdr"] = o.MagpieMdr.Get()
	}
	if o.MagpieFee.IsSet() {
		toSerialize["magpie_fee"] = o.MagpieFee.Get()
	}
	if o.MerchantNetAmount.IsSet() {
		toSerialize["merchant_net_amount"] = o.MerchantNetAmount.Get()
	}
	if o.PaymentSource.IsSet() {
		toSerialize["payment_source"] = o.PaymentSource.Get()
	}
	if o.PaidAt.IsSet() {
		toSerialize["paid_at"] = o.PaidAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["livemode"] = o.Livemode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"qrph_id",
		"created_at",
		"updated_at",
		"livemode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentResponse := _PaymentResponse{}

	err = json.Unmarshal(data, &varPaymentResponse)

	if err != nil {
		return err
	}

	*o = PaymentResponse(varPaymentResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "qrph_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "magpie_mdr")
		delete(additionalProperties, "magpie_fee")
		delete(additionalProperties, "merchant_net_amount")
		delete(additionalProperties, "payment_source")
		delete(additionalProperties, "paid_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "livemode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentResponse struct {
	value *PaymentResponse
	isSet bool
}

func (v NullablePaymentResponse) Get() *PaymentResponse {
	return v.value
}

func (v *NullablePaymentResponse) Set(val *PaymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentResponse(val *PaymentResponse) *NullablePaymentResponse {
	return &NullablePaymentResponse{value: val, isSet: true}
}

func (v NullablePaymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


