/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CanonicalCreateQRReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanonicalCreateQRReq{}

// CanonicalCreateQRReq struct for CanonicalCreateQRReq
type CanonicalCreateQRReq struct {
	// Client-provided identifier used to correlate the QRPh request.
	ReferenceId string `json:"reference_id"`
	// QR type, dynamic for fixed payments or static for amount-less flows.
	Type string `json:"type"`
	Amount NullableInt32 `json:"amount,omitempty"`
	SubmerchantId NullableString `json:"submerchant_id,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _CanonicalCreateQRReq CanonicalCreateQRReq

// NewCanonicalCreateQRReq instantiates a new CanonicalCreateQRReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanonicalCreateQRReq(referenceId string, type_ string) *CanonicalCreateQRReq {
	this := CanonicalCreateQRReq{}
	this.ReferenceId = referenceId
	this.Type = type_
	return &this
}

// NewCanonicalCreateQRReqWithDefaults instantiates a new CanonicalCreateQRReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanonicalCreateQRReqWithDefaults() *CanonicalCreateQRReq {
	this := CanonicalCreateQRReq{}
	return &this
}

// GetReferenceId returns the ReferenceId field value
func (o *CanonicalCreateQRReq) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *CanonicalCreateQRReq) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *CanonicalCreateQRReq) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetType returns the Type field value
func (o *CanonicalCreateQRReq) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CanonicalCreateQRReq) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CanonicalCreateQRReq) SetType(v string) {
	o.Type = v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CanonicalCreateQRReq) GetAmount() int32 {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret int32
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CanonicalCreateQRReq) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *CanonicalCreateQRReq) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableInt32 and assigns it to the Amount field.
func (o *CanonicalCreateQRReq) SetAmount(v int32) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *CanonicalCreateQRReq) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *CanonicalCreateQRReq) UnsetAmount() {
	o.Amount.Unset()
}

// GetSubmerchantId returns the SubmerchantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CanonicalCreateQRReq) GetSubmerchantId() string {
	if o == nil || IsNil(o.SubmerchantId.Get()) {
		var ret string
		return ret
	}
	return *o.SubmerchantId.Get()
}

// GetSubmerchantIdOk returns a tuple with the SubmerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CanonicalCreateQRReq) GetSubmerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubmerchantId.Get(), o.SubmerchantId.IsSet()
}

// HasSubmerchantId returns a boolean if a field has been set.
func (o *CanonicalCreateQRReq) HasSubmerchantId() bool {
	if o != nil && o.SubmerchantId.IsSet() {
		return true
	}

	return false
}

// SetSubmerchantId gets a reference to the given NullableString and assigns it to the SubmerchantId field.
func (o *CanonicalCreateQRReq) SetSubmerchantId(v string) {
	o.SubmerchantId.Set(&v)
}
// SetSubmerchantIdNil sets the value for SubmerchantId to be an explicit nil
func (o *CanonicalCreateQRReq) SetSubmerchantIdNil() {
	o.SubmerchantId.Set(nil)
}

// UnsetSubmerchantId ensures that no value is present for SubmerchantId, not even an explicit nil
func (o *CanonicalCreateQRReq) UnsetSubmerchantId() {
	o.SubmerchantId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CanonicalCreateQRReq) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CanonicalCreateQRReq) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CanonicalCreateQRReq) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CanonicalCreateQRReq) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o CanonicalCreateQRReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanonicalCreateQRReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reference_id"] = o.ReferenceId
	toSerialize["type"] = o.Type
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if o.SubmerchantId.IsSet() {
		toSerialize["submerchant_id"] = o.SubmerchantId.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CanonicalCreateQRReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reference_id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCanonicalCreateQRReq := _CanonicalCreateQRReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCanonicalCreateQRReq)

	if err != nil {
		return err
	}

	*o = CanonicalCreateQRReq(varCanonicalCreateQRReq)

	return err
}

type NullableCanonicalCreateQRReq struct {
	value *CanonicalCreateQRReq
	isSet bool
}

func (v NullableCanonicalCreateQRReq) Get() *CanonicalCreateQRReq {
	return v.value
}

func (v *NullableCanonicalCreateQRReq) Set(val *CanonicalCreateQRReq) {
	v.value = val
	v.isSet = true
}

func (v NullableCanonicalCreateQRReq) IsSet() bool {
	return v.isSet
}

func (v *NullableCanonicalCreateQRReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanonicalCreateQRReq(val *CanonicalCreateQRReq) *NullableCanonicalCreateQRReq {
	return &NullableCanonicalCreateQRReq{value: val, isSet: true}
}

func (v NullableCanonicalCreateQRReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanonicalCreateQRReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


