/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentCollectionResponse{}

// PaymentCollectionResponse struct for PaymentCollectionResponse
type PaymentCollectionResponse struct {
	Data []PaymentResponse `json:"data"`
	Limit int32 `json:"limit"`
	NextCursor string `json:"next_cursor"`
}

type _PaymentCollectionResponse PaymentCollectionResponse

// NewPaymentCollectionResponse instantiates a new PaymentCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentCollectionResponse(data []PaymentResponse, limit int32, nextCursor string) *PaymentCollectionResponse {
	this := PaymentCollectionResponse{}
	this.Data = data
	this.Limit = limit
	this.NextCursor = nextCursor
	return &this
}

// NewPaymentCollectionResponseWithDefaults instantiates a new PaymentCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentCollectionResponseWithDefaults() *PaymentCollectionResponse {
	this := PaymentCollectionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PaymentCollectionResponse) GetData() []PaymentResponse {
	if o == nil {
		var ret []PaymentResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaymentCollectionResponse) GetDataOk() ([]PaymentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaymentCollectionResponse) SetData(v []PaymentResponse) {
	o.Data = v
}

// GetLimit returns the Limit field value
func (o *PaymentCollectionResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *PaymentCollectionResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *PaymentCollectionResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value
func (o *PaymentCollectionResponse) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *PaymentCollectionResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *PaymentCollectionResponse) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o PaymentCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["limit"] = o.Limit
	toSerialize["next_cursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *PaymentCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"limit",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentCollectionResponse := _PaymentCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentCollectionResponse)

	if err != nil {
		return err
	}

	*o = PaymentCollectionResponse(varPaymentCollectionResponse)

	return err
}

type NullablePaymentCollectionResponse struct {
	value *PaymentCollectionResponse
	isSet bool
}

func (v NullablePaymentCollectionResponse) Get() *PaymentCollectionResponse {
	return v.value
}

func (v *NullablePaymentCollectionResponse) Set(val *PaymentCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentCollectionResponse(val *PaymentCollectionResponse) *NullablePaymentCollectionResponse {
	return &NullablePaymentCollectionResponse{value: val, isSet: true}
}

func (v NullablePaymentCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


