/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QRPhCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRPhCollectionResponse{}

// QRPhCollectionResponse struct for QRPhCollectionResponse
type QRPhCollectionResponse struct {
	Data []QRPhResponse `json:"data"`
	Limit int32 `json:"limit"`
	NextCursor string `json:"next_cursor"`
}

type _QRPhCollectionResponse QRPhCollectionResponse

// NewQRPhCollectionResponse instantiates a new QRPhCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRPhCollectionResponse(data []QRPhResponse, limit int32, nextCursor string) *QRPhCollectionResponse {
	this := QRPhCollectionResponse{}
	this.Data = data
	this.Limit = limit
	this.NextCursor = nextCursor
	return &this
}

// NewQRPhCollectionResponseWithDefaults instantiates a new QRPhCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRPhCollectionResponseWithDefaults() *QRPhCollectionResponse {
	this := QRPhCollectionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *QRPhCollectionResponse) GetData() []QRPhResponse {
	if o == nil {
		var ret []QRPhResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *QRPhCollectionResponse) GetDataOk() ([]QRPhResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *QRPhCollectionResponse) SetData(v []QRPhResponse) {
	o.Data = v
}

// GetLimit returns the Limit field value
func (o *QRPhCollectionResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *QRPhCollectionResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *QRPhCollectionResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value
func (o *QRPhCollectionResponse) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *QRPhCollectionResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *QRPhCollectionResponse) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o QRPhCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRPhCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["limit"] = o.Limit
	toSerialize["next_cursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *QRPhCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"limit",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRPhCollectionResponse := _QRPhCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQRPhCollectionResponse)

	if err != nil {
		return err
	}

	*o = QRPhCollectionResponse(varQRPhCollectionResponse)

	return err
}

type NullableQRPhCollectionResponse struct {
	value *QRPhCollectionResponse
	isSet bool
}

func (v NullableQRPhCollectionResponse) Get() *QRPhCollectionResponse {
	return v.value
}

func (v *NullableQRPhCollectionResponse) Set(val *QRPhCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQRPhCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQRPhCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRPhCollectionResponse(val *QRPhCollectionResponse) *NullableQRPhCollectionResponse {
	return &NullableQRPhCollectionResponse{value: val, isSet: true}
}

func (v NullableQRPhCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRPhCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


