/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"fmt"
)

// checks if the PayoutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutResponse{}

// PayoutResponse struct for PayoutResponse
type PayoutResponse struct {
	// Unique payout identifier.
	Id string `json:"id"`
	// Client-provided reference tying to the payout request.
	ReferenceId string `json:"reference_id"`
	// Payment channel (instapay/pesonet).
	Channel string `json:"channel"`
	// Amount in centavos.
	Amount int32 `json:"amount"`
	MagpieFee NullableInt32 `json:"magpie_fee,omitempty"`
	// Org bank account used as source.
	SourceAccountId string `json:"source_account_id"`
	// Destination bank account data.
	Destination PayoutDestinationResponse `json:"destination"`
	Purpose NullableString `json:"purpose,omitempty"`
	// Current status of the payout.
	Status string `json:"status"`
	Provider NullableString `json:"provider,omitempty"`
	// Provider-specific reference data.
	ProviderRef map[string]interface{} `json:"provider_ref,omitempty"`
	ProviderMessage NullableString `json:"provider_message,omitempty"`
	// Merchant-defined metadata.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// ISO timestamp when payout was created.
	CreatedAt string `json:"created_at"`
	// ISO timestamp when the payout was last modified.
	UpdatedAt string `json:"updated_at"`
	PostedAt NullableString `json:"posted_at,omitempty"`
	CompletedAt NullableString `json:"completed_at,omitempty"`
	FailedAt NullableString `json:"failed_at,omitempty"`
	FailureCode NullableString `json:"failure_code,omitempty"`
	FailureMessage NullableString `json:"failure_message,omitempty"`
	// True when the payout was created in live mode.
	Livemode bool `json:"livemode"`
	AdditionalProperties map[string]interface{}
}

type _PayoutResponse PayoutResponse

// NewPayoutResponse instantiates a new PayoutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutResponse(id string, referenceId string, channel string, amount int32, sourceAccountId string, destination PayoutDestinationResponse, status string, createdAt string, updatedAt string, livemode bool) *PayoutResponse {
	this := PayoutResponse{}
	this.Id = id
	this.ReferenceId = referenceId
	this.Channel = channel
	this.Amount = amount
	this.SourceAccountId = sourceAccountId
	this.Destination = destination
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Livemode = livemode
	return &this
}

// NewPayoutResponseWithDefaults instantiates a new PayoutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutResponseWithDefaults() *PayoutResponse {
	this := PayoutResponse{}
	return &this
}

// GetId returns the Id field value
func (o *PayoutResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PayoutResponse) SetId(v string) {
	o.Id = v
}

// GetReferenceId returns the ReferenceId field value
func (o *PayoutResponse) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *PayoutResponse) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetChannel returns the Channel field value
func (o *PayoutResponse) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *PayoutResponse) SetChannel(v string) {
	o.Channel = v
}

// GetAmount returns the Amount field value
func (o *PayoutResponse) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PayoutResponse) SetAmount(v int32) {
	o.Amount = v
}

// GetMagpieFee returns the MagpieFee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetMagpieFee() int32 {
	if o == nil || IsNil(o.MagpieFee.Get()) {
		var ret int32
		return ret
	}
	return *o.MagpieFee.Get()
}

// GetMagpieFeeOk returns a tuple with the MagpieFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetMagpieFeeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MagpieFee.Get(), o.MagpieFee.IsSet()
}

// HasMagpieFee returns a boolean if a field has been set.
func (o *PayoutResponse) HasMagpieFee() bool {
	if o != nil && o.MagpieFee.IsSet() {
		return true
	}

	return false
}

// SetMagpieFee gets a reference to the given NullableInt32 and assigns it to the MagpieFee field.
func (o *PayoutResponse) SetMagpieFee(v int32) {
	o.MagpieFee.Set(&v)
}
// SetMagpieFeeNil sets the value for MagpieFee to be an explicit nil
func (o *PayoutResponse) SetMagpieFeeNil() {
	o.MagpieFee.Set(nil)
}

// UnsetMagpieFee ensures that no value is present for MagpieFee, not even an explicit nil
func (o *PayoutResponse) UnsetMagpieFee() {
	o.MagpieFee.Unset()
}

// GetSourceAccountId returns the SourceAccountId field value
func (o *PayoutResponse) GetSourceAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAccountId
}

// GetSourceAccountIdOk returns a tuple with the SourceAccountId field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetSourceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAccountId, true
}

// SetSourceAccountId sets field value
func (o *PayoutResponse) SetSourceAccountId(v string) {
	o.SourceAccountId = v
}

// GetDestination returns the Destination field value
func (o *PayoutResponse) GetDestination() PayoutDestinationResponse {
	if o == nil {
		var ret PayoutDestinationResponse
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetDestinationOk() (*PayoutDestinationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *PayoutResponse) SetDestination(v PayoutDestinationResponse) {
	o.Destination = v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetPurpose() string {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret string
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *PayoutResponse) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullableString and assigns it to the Purpose field.
func (o *PayoutResponse) SetPurpose(v string) {
	o.Purpose.Set(&v)
}
// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *PayoutResponse) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *PayoutResponse) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetStatus returns the Status field value
func (o *PayoutResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PayoutResponse) SetStatus(v string) {
	o.Status = v
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *PayoutResponse) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *PayoutResponse) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *PayoutResponse) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *PayoutResponse) UnsetProvider() {
	o.Provider.Unset()
}

// GetProviderRef returns the ProviderRef field value if set, zero value otherwise.
func (o *PayoutResponse) GetProviderRef() map[string]interface{} {
	if o == nil || IsNil(o.ProviderRef) {
		var ret map[string]interface{}
		return ret
	}
	return o.ProviderRef
}

// GetProviderRefOk returns a tuple with the ProviderRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetProviderRefOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProviderRef) {
		return map[string]interface{}{}, false
	}
	return o.ProviderRef, true
}

// HasProviderRef returns a boolean if a field has been set.
func (o *PayoutResponse) HasProviderRef() bool {
	if o != nil && !IsNil(o.ProviderRef) {
		return true
	}

	return false
}

// SetProviderRef gets a reference to the given map[string]interface{} and assigns it to the ProviderRef field.
func (o *PayoutResponse) SetProviderRef(v map[string]interface{}) {
	o.ProviderRef = v
}

// GetProviderMessage returns the ProviderMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetProviderMessage() string {
	if o == nil || IsNil(o.ProviderMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ProviderMessage.Get()
}

// GetProviderMessageOk returns a tuple with the ProviderMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetProviderMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderMessage.Get(), o.ProviderMessage.IsSet()
}

// HasProviderMessage returns a boolean if a field has been set.
func (o *PayoutResponse) HasProviderMessage() bool {
	if o != nil && o.ProviderMessage.IsSet() {
		return true
	}

	return false
}

// SetProviderMessage gets a reference to the given NullableString and assigns it to the ProviderMessage field.
func (o *PayoutResponse) SetProviderMessage(v string) {
	o.ProviderMessage.Set(&v)
}
// SetProviderMessageNil sets the value for ProviderMessage to be an explicit nil
func (o *PayoutResponse) SetProviderMessageNil() {
	o.ProviderMessage.Set(nil)
}

// UnsetProviderMessage ensures that no value is present for ProviderMessage, not even an explicit nil
func (o *PayoutResponse) UnsetProviderMessage() {
	o.ProviderMessage.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PayoutResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PayoutResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PayoutResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PayoutResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PayoutResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PayoutResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PayoutResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetPostedAt returns the PostedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetPostedAt() string {
	if o == nil || IsNil(o.PostedAt.Get()) {
		var ret string
		return ret
	}
	return *o.PostedAt.Get()
}

// GetPostedAtOk returns a tuple with the PostedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetPostedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostedAt.Get(), o.PostedAt.IsSet()
}

// HasPostedAt returns a boolean if a field has been set.
func (o *PayoutResponse) HasPostedAt() bool {
	if o != nil && o.PostedAt.IsSet() {
		return true
	}

	return false
}

// SetPostedAt gets a reference to the given NullableString and assigns it to the PostedAt field.
func (o *PayoutResponse) SetPostedAt(v string) {
	o.PostedAt.Set(&v)
}
// SetPostedAtNil sets the value for PostedAt to be an explicit nil
func (o *PayoutResponse) SetPostedAtNil() {
	o.PostedAt.Set(nil)
}

// UnsetPostedAt ensures that no value is present for PostedAt, not even an explicit nil
func (o *PayoutResponse) UnsetPostedAt() {
	o.PostedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *PayoutResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *PayoutResponse) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *PayoutResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *PayoutResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetFailedAt returns the FailedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetFailedAt() string {
	if o == nil || IsNil(o.FailedAt.Get()) {
		var ret string
		return ret
	}
	return *o.FailedAt.Get()
}

// GetFailedAtOk returns a tuple with the FailedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetFailedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailedAt.Get(), o.FailedAt.IsSet()
}

// HasFailedAt returns a boolean if a field has been set.
func (o *PayoutResponse) HasFailedAt() bool {
	if o != nil && o.FailedAt.IsSet() {
		return true
	}

	return false
}

// SetFailedAt gets a reference to the given NullableString and assigns it to the FailedAt field.
func (o *PayoutResponse) SetFailedAt(v string) {
	o.FailedAt.Set(&v)
}
// SetFailedAtNil sets the value for FailedAt to be an explicit nil
func (o *PayoutResponse) SetFailedAtNil() {
	o.FailedAt.Set(nil)
}

// UnsetFailedAt ensures that no value is present for FailedAt, not even an explicit nil
func (o *PayoutResponse) UnsetFailedAt() {
	o.FailedAt.Unset()
}

// GetFailureCode returns the FailureCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetFailureCode() string {
	if o == nil || IsNil(o.FailureCode.Get()) {
		var ret string
		return ret
	}
	return *o.FailureCode.Get()
}

// GetFailureCodeOk returns a tuple with the FailureCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetFailureCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureCode.Get(), o.FailureCode.IsSet()
}

// HasFailureCode returns a boolean if a field has been set.
func (o *PayoutResponse) HasFailureCode() bool {
	if o != nil && o.FailureCode.IsSet() {
		return true
	}

	return false
}

// SetFailureCode gets a reference to the given NullableString and assigns it to the FailureCode field.
func (o *PayoutResponse) SetFailureCode(v string) {
	o.FailureCode.Set(&v)
}
// SetFailureCodeNil sets the value for FailureCode to be an explicit nil
func (o *PayoutResponse) SetFailureCodeNil() {
	o.FailureCode.Set(nil)
}

// UnsetFailureCode ensures that no value is present for FailureCode, not even an explicit nil
func (o *PayoutResponse) UnsetFailureCode() {
	o.FailureCode.Unset()
}

// GetFailureMessage returns the FailureMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutResponse) GetFailureMessage() string {
	if o == nil || IsNil(o.FailureMessage.Get()) {
		var ret string
		return ret
	}
	return *o.FailureMessage.Get()
}

// GetFailureMessageOk returns a tuple with the FailureMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutResponse) GetFailureMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureMessage.Get(), o.FailureMessage.IsSet()
}

// HasFailureMessage returns a boolean if a field has been set.
func (o *PayoutResponse) HasFailureMessage() bool {
	if o != nil && o.FailureMessage.IsSet() {
		return true
	}

	return false
}

// SetFailureMessage gets a reference to the given NullableString and assigns it to the FailureMessage field.
func (o *PayoutResponse) SetFailureMessage(v string) {
	o.FailureMessage.Set(&v)
}
// SetFailureMessageNil sets the value for FailureMessage to be an explicit nil
func (o *PayoutResponse) SetFailureMessageNil() {
	o.FailureMessage.Set(nil)
}

// UnsetFailureMessage ensures that no value is present for FailureMessage, not even an explicit nil
func (o *PayoutResponse) UnsetFailureMessage() {
	o.FailureMessage.Unset()
}

// GetLivemode returns the Livemode field value
func (o *PayoutResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *PayoutResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *PayoutResponse) SetLivemode(v bool) {
	o.Livemode = v
}

func (o PayoutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["reference_id"] = o.ReferenceId
	toSerialize["channel"] = o.Channel
	toSerialize["amount"] = o.Amount
	if o.MagpieFee.IsSet() {
		toSerialize["magpie_fee"] = o.MagpieFee.Get()
	}
	toSerialize["source_account_id"] = o.SourceAccountId
	toSerialize["destination"] = o.Destination
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	toSerialize["status"] = o.Status
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if !IsNil(o.ProviderRef) {
		toSerialize["provider_ref"] = o.ProviderRef
	}
	if o.ProviderMessage.IsSet() {
		toSerialize["provider_message"] = o.ProviderMessage.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if o.PostedAt.IsSet() {
		toSerialize["posted_at"] = o.PostedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.FailedAt.IsSet() {
		toSerialize["failed_at"] = o.FailedAt.Get()
	}
	if o.FailureCode.IsSet() {
		toSerialize["failure_code"] = o.FailureCode.Get()
	}
	if o.FailureMessage.IsSet() {
		toSerialize["failure_message"] = o.FailureMessage.Get()
	}
	toSerialize["livemode"] = o.Livemode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PayoutResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"reference_id",
		"channel",
		"amount",
		"source_account_id",
		"destination",
		"status",
		"created_at",
		"updated_at",
		"livemode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutResponse := _PayoutResponse{}

	err = json.Unmarshal(data, &varPayoutResponse)

	if err != nil {
		return err
	}

	*o = PayoutResponse(varPayoutResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "reference_id")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "magpie_fee")
		delete(additionalProperties, "source_account_id")
		delete(additionalProperties, "destination")
		delete(additionalProperties, "purpose")
		delete(additionalProperties, "status")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "provider_ref")
		delete(additionalProperties, "provider_message")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "posted_at")
		delete(additionalProperties, "completed_at")
		delete(additionalProperties, "failed_at")
		delete(additionalProperties, "failure_code")
		delete(additionalProperties, "failure_message")
		delete(additionalProperties, "livemode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePayoutResponse struct {
	value *PayoutResponse
	isSet bool
}

func (v NullablePayoutResponse) Get() *PayoutResponse {
	return v.value
}

func (v *NullablePayoutResponse) Set(val *PayoutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutResponse(val *PayoutResponse) *NullablePayoutResponse {
	return &NullablePayoutResponse{value: val, isSet: true}
}

func (v NullablePayoutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


