/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"fmt"
)

// checks if the QRPhResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRPhResponse{}

// QRPhResponse struct for QRPhResponse
type QRPhResponse struct {
	// Unique identifier for the QRPh request.
	Id string `json:"id"`
	// Client-provided reference for correlating the request.
	ReferenceId string `json:"reference_id"`
	// QR code type, either static or dynamic.
	Type string `json:"type"`
	Amount NullableInt32 `json:"amount,omitempty"`
	SubmerchantId NullableString `json:"submerchant_id,omitempty"`
	// Current status of the QRPh request.
	Status string `json:"status"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	QrphPayload NullableString `json:"qrph_payload,omitempty"`
	QrphImage NullableString `json:"qrph_image,omitempty"`
	CheckoutUrl NullableString `json:"checkout_url,omitempty"`
	PaymentId NullableString `json:"payment_id,omitempty"`
	PaidAt NullableString `json:"paid_at,omitempty"`
	ExpiresAt NullableString `json:"expires_at,omitempty"`
	CancelledAt NullableString `json:"cancelled_at,omitempty"`
	CancellationReason NullableString `json:"cancellation_reason,omitempty"`
	// ISO timestamp when the QRPh request was created.
	CreatedAt string `json:"created_at"`
	// ISO timestamp when the QRPh request was last updated.
	UpdatedAt string `json:"updated_at"`
	// Indicates whether the request was created in live or test mode.
	Livemode bool `json:"livemode"`
	AdditionalProperties map[string]interface{}
}

type _QRPhResponse QRPhResponse

// NewQRPhResponse instantiates a new QRPhResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRPhResponse(id string, referenceId string, type_ string, status string, createdAt string, updatedAt string, livemode bool) *QRPhResponse {
	this := QRPhResponse{}
	this.Id = id
	this.ReferenceId = referenceId
	this.Type = type_
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Livemode = livemode
	return &this
}

// NewQRPhResponseWithDefaults instantiates a new QRPhResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRPhResponseWithDefaults() *QRPhResponse {
	this := QRPhResponse{}
	return &this
}

// GetId returns the Id field value
func (o *QRPhResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QRPhResponse) SetId(v string) {
	o.Id = v
}

// GetReferenceId returns the ReferenceId field value
func (o *QRPhResponse) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *QRPhResponse) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetType returns the Type field value
func (o *QRPhResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QRPhResponse) SetType(v string) {
	o.Type = v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetAmount() int32 {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret int32
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *QRPhResponse) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableInt32 and assigns it to the Amount field.
func (o *QRPhResponse) SetAmount(v int32) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *QRPhResponse) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *QRPhResponse) UnsetAmount() {
	o.Amount.Unset()
}

// GetSubmerchantId returns the SubmerchantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetSubmerchantId() string {
	if o == nil || IsNil(o.SubmerchantId.Get()) {
		var ret string
		return ret
	}
	return *o.SubmerchantId.Get()
}

// GetSubmerchantIdOk returns a tuple with the SubmerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetSubmerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubmerchantId.Get(), o.SubmerchantId.IsSet()
}

// HasSubmerchantId returns a boolean if a field has been set.
func (o *QRPhResponse) HasSubmerchantId() bool {
	if o != nil && o.SubmerchantId.IsSet() {
		return true
	}

	return false
}

// SetSubmerchantId gets a reference to the given NullableString and assigns it to the SubmerchantId field.
func (o *QRPhResponse) SetSubmerchantId(v string) {
	o.SubmerchantId.Set(&v)
}
// SetSubmerchantIdNil sets the value for SubmerchantId to be an explicit nil
func (o *QRPhResponse) SetSubmerchantIdNil() {
	o.SubmerchantId.Set(nil)
}

// UnsetSubmerchantId ensures that no value is present for SubmerchantId, not even an explicit nil
func (o *QRPhResponse) UnsetSubmerchantId() {
	o.SubmerchantId.Unset()
}

// GetStatus returns the Status field value
func (o *QRPhResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *QRPhResponse) SetStatus(v string) {
	o.Status = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *QRPhResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *QRPhResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetQrphPayload returns the QrphPayload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetQrphPayload() string {
	if o == nil || IsNil(o.QrphPayload.Get()) {
		var ret string
		return ret
	}
	return *o.QrphPayload.Get()
}

// GetQrphPayloadOk returns a tuple with the QrphPayload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetQrphPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QrphPayload.Get(), o.QrphPayload.IsSet()
}

// HasQrphPayload returns a boolean if a field has been set.
func (o *QRPhResponse) HasQrphPayload() bool {
	if o != nil && o.QrphPayload.IsSet() {
		return true
	}

	return false
}

// SetQrphPayload gets a reference to the given NullableString and assigns it to the QrphPayload field.
func (o *QRPhResponse) SetQrphPayload(v string) {
	o.QrphPayload.Set(&v)
}
// SetQrphPayloadNil sets the value for QrphPayload to be an explicit nil
func (o *QRPhResponse) SetQrphPayloadNil() {
	o.QrphPayload.Set(nil)
}

// UnsetQrphPayload ensures that no value is present for QrphPayload, not even an explicit nil
func (o *QRPhResponse) UnsetQrphPayload() {
	o.QrphPayload.Unset()
}

// GetQrphImage returns the QrphImage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetQrphImage() string {
	if o == nil || IsNil(o.QrphImage.Get()) {
		var ret string
		return ret
	}
	return *o.QrphImage.Get()
}

// GetQrphImageOk returns a tuple with the QrphImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetQrphImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QrphImage.Get(), o.QrphImage.IsSet()
}

// HasQrphImage returns a boolean if a field has been set.
func (o *QRPhResponse) HasQrphImage() bool {
	if o != nil && o.QrphImage.IsSet() {
		return true
	}

	return false
}

// SetQrphImage gets a reference to the given NullableString and assigns it to the QrphImage field.
func (o *QRPhResponse) SetQrphImage(v string) {
	o.QrphImage.Set(&v)
}
// SetQrphImageNil sets the value for QrphImage to be an explicit nil
func (o *QRPhResponse) SetQrphImageNil() {
	o.QrphImage.Set(nil)
}

// UnsetQrphImage ensures that no value is present for QrphImage, not even an explicit nil
func (o *QRPhResponse) UnsetQrphImage() {
	o.QrphImage.Unset()
}

// GetCheckoutUrl returns the CheckoutUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetCheckoutUrl() string {
	if o == nil || IsNil(o.CheckoutUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CheckoutUrl.Get()
}

// GetCheckoutUrlOk returns a tuple with the CheckoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetCheckoutUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckoutUrl.Get(), o.CheckoutUrl.IsSet()
}

// HasCheckoutUrl returns a boolean if a field has been set.
func (o *QRPhResponse) HasCheckoutUrl() bool {
	if o != nil && o.CheckoutUrl.IsSet() {
		return true
	}

	return false
}

// SetCheckoutUrl gets a reference to the given NullableString and assigns it to the CheckoutUrl field.
func (o *QRPhResponse) SetCheckoutUrl(v string) {
	o.CheckoutUrl.Set(&v)
}
// SetCheckoutUrlNil sets the value for CheckoutUrl to be an explicit nil
func (o *QRPhResponse) SetCheckoutUrlNil() {
	o.CheckoutUrl.Set(nil)
}

// UnsetCheckoutUrl ensures that no value is present for CheckoutUrl, not even an explicit nil
func (o *QRPhResponse) UnsetCheckoutUrl() {
	o.CheckoutUrl.Unset()
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId.Get()) {
		var ret string
		return ret
	}
	return *o.PaymentId.Get()
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentId.Get(), o.PaymentId.IsSet()
}

// HasPaymentId returns a boolean if a field has been set.
func (o *QRPhResponse) HasPaymentId() bool {
	if o != nil && o.PaymentId.IsSet() {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given NullableString and assigns it to the PaymentId field.
func (o *QRPhResponse) SetPaymentId(v string) {
	o.PaymentId.Set(&v)
}
// SetPaymentIdNil sets the value for PaymentId to be an explicit nil
func (o *QRPhResponse) SetPaymentIdNil() {
	o.PaymentId.Set(nil)
}

// UnsetPaymentId ensures that no value is present for PaymentId, not even an explicit nil
func (o *QRPhResponse) UnsetPaymentId() {
	o.PaymentId.Unset()
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetPaidAt() string {
	if o == nil || IsNil(o.PaidAt.Get()) {
		var ret string
		return ret
	}
	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetPaidAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// HasPaidAt returns a boolean if a field has been set.
func (o *QRPhResponse) HasPaidAt() bool {
	if o != nil && o.PaidAt.IsSet() {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given NullableString and assigns it to the PaidAt field.
func (o *QRPhResponse) SetPaidAt(v string) {
	o.PaidAt.Set(&v)
}
// SetPaidAtNil sets the value for PaidAt to be an explicit nil
func (o *QRPhResponse) SetPaidAtNil() {
	o.PaidAt.Set(nil)
}

// UnsetPaidAt ensures that no value is present for PaidAt, not even an explicit nil
func (o *QRPhResponse) UnsetPaidAt() {
	o.PaidAt.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *QRPhResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *QRPhResponse) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *QRPhResponse) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *QRPhResponse) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetCancelledAt returns the CancelledAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetCancelledAt() string {
	if o == nil || IsNil(o.CancelledAt.Get()) {
		var ret string
		return ret
	}
	return *o.CancelledAt.Get()
}

// GetCancelledAtOk returns a tuple with the CancelledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetCancelledAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancelledAt.Get(), o.CancelledAt.IsSet()
}

// HasCancelledAt returns a boolean if a field has been set.
func (o *QRPhResponse) HasCancelledAt() bool {
	if o != nil && o.CancelledAt.IsSet() {
		return true
	}

	return false
}

// SetCancelledAt gets a reference to the given NullableString and assigns it to the CancelledAt field.
func (o *QRPhResponse) SetCancelledAt(v string) {
	o.CancelledAt.Set(&v)
}
// SetCancelledAtNil sets the value for CancelledAt to be an explicit nil
func (o *QRPhResponse) SetCancelledAtNil() {
	o.CancelledAt.Set(nil)
}

// UnsetCancelledAt ensures that no value is present for CancelledAt, not even an explicit nil
func (o *QRPhResponse) UnsetCancelledAt() {
	o.CancelledAt.Unset()
}

// GetCancellationReason returns the CancellationReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QRPhResponse) GetCancellationReason() string {
	if o == nil || IsNil(o.CancellationReason.Get()) {
		var ret string
		return ret
	}
	return *o.CancellationReason.Get()
}

// GetCancellationReasonOk returns a tuple with the CancellationReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QRPhResponse) GetCancellationReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancellationReason.Get(), o.CancellationReason.IsSet()
}

// HasCancellationReason returns a boolean if a field has been set.
func (o *QRPhResponse) HasCancellationReason() bool {
	if o != nil && o.CancellationReason.IsSet() {
		return true
	}

	return false
}

// SetCancellationReason gets a reference to the given NullableString and assigns it to the CancellationReason field.
func (o *QRPhResponse) SetCancellationReason(v string) {
	o.CancellationReason.Set(&v)
}
// SetCancellationReasonNil sets the value for CancellationReason to be an explicit nil
func (o *QRPhResponse) SetCancellationReasonNil() {
	o.CancellationReason.Set(nil)
}

// UnsetCancellationReason ensures that no value is present for CancellationReason, not even an explicit nil
func (o *QRPhResponse) UnsetCancellationReason() {
	o.CancellationReason.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *QRPhResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *QRPhResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *QRPhResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *QRPhResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetLivemode returns the Livemode field value
func (o *QRPhResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *QRPhResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *QRPhResponse) SetLivemode(v bool) {
	o.Livemode = v
}

func (o QRPhResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRPhResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["reference_id"] = o.ReferenceId
	toSerialize["type"] = o.Type
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if o.SubmerchantId.IsSet() {
		toSerialize["submerchant_id"] = o.SubmerchantId.Get()
	}
	toSerialize["status"] = o.Status
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.QrphPayload.IsSet() {
		toSerialize["qrph_payload"] = o.QrphPayload.Get()
	}
	if o.QrphImage.IsSet() {
		toSerialize["qrph_image"] = o.QrphImage.Get()
	}
	if o.CheckoutUrl.IsSet() {
		toSerialize["checkout_url"] = o.CheckoutUrl.Get()
	}
	if o.PaymentId.IsSet() {
		toSerialize["payment_id"] = o.PaymentId.Get()
	}
	if o.PaidAt.IsSet() {
		toSerialize["paid_at"] = o.PaidAt.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.CancelledAt.IsSet() {
		toSerialize["cancelled_at"] = o.CancelledAt.Get()
	}
	if o.CancellationReason.IsSet() {
		toSerialize["cancellation_reason"] = o.CancellationReason.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["livemode"] = o.Livemode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QRPhResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"reference_id",
		"type",
		"status",
		"created_at",
		"updated_at",
		"livemode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRPhResponse := _QRPhResponse{}

	err = json.Unmarshal(data, &varQRPhResponse)

	if err != nil {
		return err
	}

	*o = QRPhResponse(varQRPhResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "reference_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "submerchant_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "qrph_payload")
		delete(additionalProperties, "qrph_image")
		delete(additionalProperties, "checkout_url")
		delete(additionalProperties, "payment_id")
		delete(additionalProperties, "paid_at")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "cancelled_at")
		delete(additionalProperties, "cancellation_reason")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "livemode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQRPhResponse struct {
	value *QRPhResponse
	isSet bool
}

func (v NullableQRPhResponse) Get() *QRPhResponse {
	return v.value
}

func (v *NullableQRPhResponse) Set(val *QRPhResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQRPhResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQRPhResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRPhResponse(val *QRPhResponse) *NullableQRPhResponse {
	return &NullableQRPhResponse{value: val, isSet: true}
}

func (v NullableQRPhResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRPhResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


