/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutDestination{}

// PayoutDestination struct for PayoutDestination
type PayoutDestination struct {
	FirstName NullableString `json:"first_name,omitempty"`
	LastName NullableString `json:"last_name,omitempty"`
	// Bank code for the beneficiary account.
	BankCode string `json:"bank_code"`
	// Beneficiary account number.
	AccountNumber string `json:"account_number"`
}

type _PayoutDestination PayoutDestination

// NewPayoutDestination instantiates a new PayoutDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutDestination(bankCode string, accountNumber string) *PayoutDestination {
	this := PayoutDestination{}
	this.BankCode = bankCode
	this.AccountNumber = accountNumber
	return &this
}

// NewPayoutDestinationWithDefaults instantiates a new PayoutDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutDestinationWithDefaults() *PayoutDestination {
	this := PayoutDestination{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutDestination) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutDestination) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *PayoutDestination) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *PayoutDestination) SetFirstName(v string) {
	o.FirstName.Set(&v)
}
// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *PayoutDestination) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *PayoutDestination) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutDestination) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutDestination) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *PayoutDestination) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *PayoutDestination) SetLastName(v string) {
	o.LastName.Set(&v)
}
// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *PayoutDestination) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *PayoutDestination) UnsetLastName() {
	o.LastName.Unset()
}

// GetBankCode returns the BankCode field value
func (o *PayoutDestination) GetBankCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankCode
}

// GetBankCodeOk returns a tuple with the BankCode field value
// and a boolean to check if the value has been set.
func (o *PayoutDestination) GetBankCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankCode, true
}

// SetBankCode sets field value
func (o *PayoutDestination) SetBankCode(v string) {
	o.BankCode = v
}

// GetAccountNumber returns the AccountNumber field value
func (o *PayoutDestination) GetAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value
// and a boolean to check if the value has been set.
func (o *PayoutDestination) GetAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountNumber, true
}

// SetAccountNumber sets field value
func (o *PayoutDestination) SetAccountNumber(v string) {
	o.AccountNumber = v
}

func (o PayoutDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FirstName.IsSet() {
		toSerialize["first_name"] = o.FirstName.Get()
	}
	if o.LastName.IsSet() {
		toSerialize["last_name"] = o.LastName.Get()
	}
	toSerialize["bank_code"] = o.BankCode
	toSerialize["account_number"] = o.AccountNumber
	return toSerialize, nil
}

func (o *PayoutDestination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_code",
		"account_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutDestination := _PayoutDestination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutDestination)

	if err != nil {
		return err
	}

	*o = PayoutDestination(varPayoutDestination)

	return err
}

type NullablePayoutDestination struct {
	value *PayoutDestination
	isSet bool
}

func (v NullablePayoutDestination) Get() *PayoutDestination {
	return v.value
}

func (v *NullablePayoutDestination) Set(val *PayoutDestination) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutDestination) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutDestination(val *PayoutDestination) *NullablePayoutDestination {
	return &NullablePayoutDestination{value: val, isSet: true}
}

func (v NullablePayoutDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


