/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankCodeCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankCodeCollection{}

// BankCodeCollection struct for BankCodeCollection
type BankCodeCollection struct {
	Data []BankCodeEntry `json:"data"`
}

type _BankCodeCollection BankCodeCollection

// NewBankCodeCollection instantiates a new BankCodeCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankCodeCollection(data []BankCodeEntry) *BankCodeCollection {
	this := BankCodeCollection{}
	this.Data = data
	return &this
}

// NewBankCodeCollectionWithDefaults instantiates a new BankCodeCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankCodeCollectionWithDefaults() *BankCodeCollection {
	this := BankCodeCollection{}
	return &this
}

// GetData returns the Data field value
func (o *BankCodeCollection) GetData() []BankCodeEntry {
	if o == nil {
		var ret []BankCodeEntry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BankCodeCollection) GetDataOk() ([]BankCodeEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BankCodeCollection) SetData(v []BankCodeEntry) {
	o.Data = v
}

func (o BankCodeCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankCodeCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BankCodeCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankCodeCollection := _BankCodeCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankCodeCollection)

	if err != nil {
		return err
	}

	*o = BankCodeCollection(varBankCodeCollection)

	return err
}

type NullableBankCodeCollection struct {
	value *BankCodeCollection
	isSet bool
}

func (v NullableBankCodeCollection) Get() *BankCodeCollection {
	return v.value
}

func (v *NullableBankCodeCollection) Set(val *BankCodeCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableBankCodeCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableBankCodeCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankCodeCollection(val *BankCodeCollection) *NullableBankCodeCollection {
	return &NullableBankCodeCollection{value: val, isSet: true}
}

func (v NullableBankCodeCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankCodeCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


