/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutCreateRequest{}

// PayoutCreateRequest struct for PayoutCreateRequest
type PayoutCreateRequest struct {
	// Client-provided reference for the payout.
	ReferenceId string `json:"reference_id"`
	// Channel to use for the payout.
	Channel string `json:"channel"`
	// Amount in centavos.
	Amount int32 `json:"amount"`
	// Org bank account ID to debit.
	SourceAccountId string `json:"source_account_id"`
	// Destination account details.
	Destination PayoutDestination `json:"destination"`
	Purpose NullableString `json:"purpose,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _PayoutCreateRequest PayoutCreateRequest

// NewPayoutCreateRequest instantiates a new PayoutCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutCreateRequest(referenceId string, channel string, amount int32, sourceAccountId string, destination PayoutDestination) *PayoutCreateRequest {
	this := PayoutCreateRequest{}
	this.ReferenceId = referenceId
	this.Channel = channel
	this.Amount = amount
	this.SourceAccountId = sourceAccountId
	this.Destination = destination
	return &this
}

// NewPayoutCreateRequestWithDefaults instantiates a new PayoutCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutCreateRequestWithDefaults() *PayoutCreateRequest {
	this := PayoutCreateRequest{}
	return &this
}

// GetReferenceId returns the ReferenceId field value
func (o *PayoutCreateRequest) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *PayoutCreateRequest) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *PayoutCreateRequest) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetChannel returns the Channel field value
func (o *PayoutCreateRequest) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *PayoutCreateRequest) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *PayoutCreateRequest) SetChannel(v string) {
	o.Channel = v
}

// GetAmount returns the Amount field value
func (o *PayoutCreateRequest) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PayoutCreateRequest) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PayoutCreateRequest) SetAmount(v int32) {
	o.Amount = v
}

// GetSourceAccountId returns the SourceAccountId field value
func (o *PayoutCreateRequest) GetSourceAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAccountId
}

// GetSourceAccountIdOk returns a tuple with the SourceAccountId field value
// and a boolean to check if the value has been set.
func (o *PayoutCreateRequest) GetSourceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAccountId, true
}

// SetSourceAccountId sets field value
func (o *PayoutCreateRequest) SetSourceAccountId(v string) {
	o.SourceAccountId = v
}

// GetDestination returns the Destination field value
func (o *PayoutCreateRequest) GetDestination() PayoutDestination {
	if o == nil {
		var ret PayoutDestination
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *PayoutCreateRequest) GetDestinationOk() (*PayoutDestination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *PayoutCreateRequest) SetDestination(v PayoutDestination) {
	o.Destination = v
}

// GetPurpose returns the Purpose field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutCreateRequest) GetPurpose() string {
	if o == nil || IsNil(o.Purpose.Get()) {
		var ret string
		return ret
	}
	return *o.Purpose.Get()
}

// GetPurposeOk returns a tuple with the Purpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutCreateRequest) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purpose.Get(), o.Purpose.IsSet()
}

// HasPurpose returns a boolean if a field has been set.
func (o *PayoutCreateRequest) HasPurpose() bool {
	if o != nil && o.Purpose.IsSet() {
		return true
	}

	return false
}

// SetPurpose gets a reference to the given NullableString and assigns it to the Purpose field.
func (o *PayoutCreateRequest) SetPurpose(v string) {
	o.Purpose.Set(&v)
}
// SetPurposeNil sets the value for Purpose to be an explicit nil
func (o *PayoutCreateRequest) SetPurposeNil() {
	o.Purpose.Set(nil)
}

// UnsetPurpose ensures that no value is present for Purpose, not even an explicit nil
func (o *PayoutCreateRequest) UnsetPurpose() {
	o.Purpose.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayoutCreateRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayoutCreateRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PayoutCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PayoutCreateRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o PayoutCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reference_id"] = o.ReferenceId
	toSerialize["channel"] = o.Channel
	toSerialize["amount"] = o.Amount
	toSerialize["source_account_id"] = o.SourceAccountId
	toSerialize["destination"] = o.Destination
	if o.Purpose.IsSet() {
		toSerialize["purpose"] = o.Purpose.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *PayoutCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reference_id",
		"channel",
		"amount",
		"source_account_id",
		"destination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutCreateRequest := _PayoutCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutCreateRequest)

	if err != nil {
		return err
	}

	*o = PayoutCreateRequest(varPayoutCreateRequest)

	return err
}

type NullablePayoutCreateRequest struct {
	value *PayoutCreateRequest
	isSet bool
}

func (v NullablePayoutCreateRequest) Get() *PayoutCreateRequest {
	return v.value
}

func (v *NullablePayoutCreateRequest) Set(val *PayoutCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutCreateRequest(val *PayoutCreateRequest) *NullablePayoutCreateRequest {
	return &NullablePayoutCreateRequest{value: val, isSet: true}
}

func (v NullablePayoutCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


