/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankCodeEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankCodeEntry{}

// BankCodeEntry struct for BankCodeEntry
type BankCodeEntry struct {
	Code string `json:"code"`
	Name NullableString `json:"name,omitempty"`
}

type _BankCodeEntry BankCodeEntry

// NewBankCodeEntry instantiates a new BankCodeEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankCodeEntry(code string) *BankCodeEntry {
	this := BankCodeEntry{}
	this.Code = code
	return &this
}

// NewBankCodeEntryWithDefaults instantiates a new BankCodeEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankCodeEntryWithDefaults() *BankCodeEntry {
	this := BankCodeEntry{}
	return &this
}

// GetCode returns the Code field value
func (o *BankCodeEntry) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *BankCodeEntry) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *BankCodeEntry) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BankCodeEntry) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BankCodeEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *BankCodeEntry) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *BankCodeEntry) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *BankCodeEntry) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *BankCodeEntry) UnsetName() {
	o.Name.Unset()
}

func (o BankCodeEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankCodeEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

func (o *BankCodeEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankCodeEntry := _BankCodeEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankCodeEntry)

	if err != nil {
		return err
	}

	*o = BankCodeEntry(varBankCodeEntry)

	return err
}

type NullableBankCodeEntry struct {
	value *BankCodeEntry
	isSet bool
}

func (v NullableBankCodeEntry) Get() *BankCodeEntry {
	return v.value
}

func (v *NullableBankCodeEntry) Set(val *BankCodeEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableBankCodeEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableBankCodeEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankCodeEntry(val *BankCodeEntry) *NullableBankCodeEntry {
	return &NullableBankCodeEntry{value: val, isSet: true}
}

func (v NullableBankCodeEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankCodeEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


