/*
Magpie API Documentation

Magpie API for QRPh and Disbursement services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magpiepay

import (
	"encoding/json"
)

// checks if the CancelQRPhRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelQRPhRequest{}

// CancelQRPhRequest struct for CancelQRPhRequest
type CancelQRPhRequest struct {
	CancellationReason NullableString `json:"cancellation_reason,omitempty"`
}

// NewCancelQRPhRequest instantiates a new CancelQRPhRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelQRPhRequest() *CancelQRPhRequest {
	this := CancelQRPhRequest{}
	return &this
}

// NewCancelQRPhRequestWithDefaults instantiates a new CancelQRPhRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelQRPhRequestWithDefaults() *CancelQRPhRequest {
	this := CancelQRPhRequest{}
	return &this
}

// GetCancellationReason returns the CancellationReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CancelQRPhRequest) GetCancellationReason() string {
	if o == nil || IsNil(o.CancellationReason.Get()) {
		var ret string
		return ret
	}
	return *o.CancellationReason.Get()
}

// GetCancellationReasonOk returns a tuple with the CancellationReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CancelQRPhRequest) GetCancellationReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancellationReason.Get(), o.CancellationReason.IsSet()
}

// HasCancellationReason returns a boolean if a field has been set.
func (o *CancelQRPhRequest) HasCancellationReason() bool {
	if o != nil && o.CancellationReason.IsSet() {
		return true
	}

	return false
}

// SetCancellationReason gets a reference to the given NullableString and assigns it to the CancellationReason field.
func (o *CancelQRPhRequest) SetCancellationReason(v string) {
	o.CancellationReason.Set(&v)
}
// SetCancellationReasonNil sets the value for CancellationReason to be an explicit nil
func (o *CancelQRPhRequest) SetCancellationReasonNil() {
	o.CancellationReason.Set(nil)
}

// UnsetCancellationReason ensures that no value is present for CancellationReason, not even an explicit nil
func (o *CancelQRPhRequest) UnsetCancellationReason() {
	o.CancellationReason.Unset()
}

func (o CancelQRPhRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelQRPhRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CancellationReason.IsSet() {
		toSerialize["cancellation_reason"] = o.CancellationReason.Get()
	}
	return toSerialize, nil
}

type NullableCancelQRPhRequest struct {
	value *CancelQRPhRequest
	isSet bool
}

func (v NullableCancelQRPhRequest) Get() *CancelQRPhRequest {
	return v.value
}

func (v *NullableCancelQRPhRequest) Set(val *CancelQRPhRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelQRPhRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelQRPhRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelQRPhRequest(val *CancelQRPhRequest) *NullableCancelQRPhRequest {
	return &NullableCancelQRPhRequest{value: val, isSet: true}
}

func (v NullableCancelQRPhRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelQRPhRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


