/*
Magpie API Documentation

Testing QRPhRequestsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package magpiepay

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/domdanao/magpiepay-sdk-go"
)

func Test_magpiepay_QRPhRequestsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test QRPhRequestsAPIService CancelQrphV1QrphIdCancelPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.QRPhRequestsAPI.CancelQrphV1QrphIdCancelPost(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QRPhRequestsAPIService CreateQrphV1QrphPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.QRPhRequestsAPI.CreateQrphV1QrphPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QRPhRequestsAPIService GetQrphStatusV1QrphIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.QRPhRequestsAPI.GetQrphStatusV1QrphIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QRPhRequestsAPIService ListQrphV1QrphGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.QRPhRequestsAPI.ListQrphV1QrphGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
