//
// CanonicalCreateQRReq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CanonicalCreateQRReq: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case _static = "static"
        case _dynamic = "dynamic"
    }
    public static let referenceIdRule = StringRule(minLength: nil, maxLength: 20, pattern: nil)
    public static let amountRule = NumericRule<Int>(minimum: nil, exclusiveMinimum: false, maximum: 5000000, exclusiveMaximum: false, multipleOf: nil)
    /** Client-provided identifier used to correlate the QRPh request. */
    public var referenceId: String
    /** QR type, dynamic for fixed payments or static for amount-less flows. */
    public var type: ModelType
    public var amount: Int?
    public var submerchantId: String?
    public var metadata: [String: AnyCodable]?

    public init(referenceId: String, type: ModelType, amount: Int? = nil, submerchantId: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.referenceId = referenceId
        self.type = type
        self.amount = amount
        self.submerchantId = submerchantId
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referenceId = "reference_id"
        case type
        case amount
        case submerchantId = "submerchant_id"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(referenceId, forKey: .referenceId)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(submerchantId, forKey: .submerchantId)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

