//
// PayoutResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PayoutResponse: Codable, JSONEncodable, Hashable {

    /** Unique payout identifier. */
    public var id: String
    /** Client-provided reference tying to the payout request. */
    public var referenceId: String
    /** Payment channel (instapay/pesonet). */
    public var channel: String
    /** Amount in centavos. */
    public var amount: Int
    public var magpieFee: Int?
    /** Org bank account used as source. */
    public var sourceAccountId: String
    /** Destination bank account data. */
    public var destination: PayoutDestinationResponse
    public var purpose: String?
    /** Current status of the payout. */
    public var status: String
    public var provider: String?
    /** Provider-specific reference data. */
    public var providerRef: [String: AnyCodable]?
    public var providerMessage: String?
    /** Merchant-defined metadata. */
    public var metadata: [String: AnyCodable]?
    /** ISO timestamp when payout was created. */
    public var createdAt: String
    /** ISO timestamp when the payout was last modified. */
    public var updatedAt: String
    public var postedAt: String?
    public var completedAt: String?
    public var failedAt: String?
    public var failureCode: String?
    public var failureMessage: String?
    /** True when the payout was created in live mode. */
    public var livemode: Bool

    public init(id: String, referenceId: String, channel: String, amount: Int, magpieFee: Int? = nil, sourceAccountId: String, destination: PayoutDestinationResponse, purpose: String? = nil, status: String, provider: String? = nil, providerRef: [String: AnyCodable]? = nil, providerMessage: String? = nil, metadata: [String: AnyCodable]? = nil, createdAt: String, updatedAt: String, postedAt: String? = nil, completedAt: String? = nil, failedAt: String? = nil, failureCode: String? = nil, failureMessage: String? = nil, livemode: Bool) {
        self.id = id
        self.referenceId = referenceId
        self.channel = channel
        self.amount = amount
        self.magpieFee = magpieFee
        self.sourceAccountId = sourceAccountId
        self.destination = destination
        self.purpose = purpose
        self.status = status
        self.provider = provider
        self.providerRef = providerRef
        self.providerMessage = providerMessage
        self.metadata = metadata
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.postedAt = postedAt
        self.completedAt = completedAt
        self.failedAt = failedAt
        self.failureCode = failureCode
        self.failureMessage = failureMessage
        self.livemode = livemode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case referenceId = "reference_id"
        case channel
        case amount
        case magpieFee = "magpie_fee"
        case sourceAccountId = "source_account_id"
        case destination
        case purpose
        case status
        case provider
        case providerRef = "provider_ref"
        case providerMessage = "provider_message"
        case metadata
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case postedAt = "posted_at"
        case completedAt = "completed_at"
        case failedAt = "failed_at"
        case failureCode = "failure_code"
        case failureMessage = "failure_message"
        case livemode
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(referenceId, forKey: .referenceId)
        try container.encode(channel, forKey: .channel)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(magpieFee, forKey: .magpieFee)
        try container.encode(sourceAccountId, forKey: .sourceAccountId)
        try container.encode(destination, forKey: .destination)
        try container.encodeIfPresent(purpose, forKey: .purpose)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(providerRef, forKey: .providerRef)
        try container.encodeIfPresent(providerMessage, forKey: .providerMessage)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(postedAt, forKey: .postedAt)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(failedAt, forKey: .failedAt)
        try container.encodeIfPresent(failureCode, forKey: .failureCode)
        try container.encodeIfPresent(failureMessage, forKey: .failureMessage)
        try container.encode(livemode, forKey: .livemode)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        referenceId = try container.decode(String.self, forKey: .referenceId)
        channel = try container.decode(String.self, forKey: .channel)
        amount = try container.decode(Int.self, forKey: .amount)
        magpieFee = try container.decodeIfPresent(Int.self, forKey: .magpieFee)
        sourceAccountId = try container.decode(String.self, forKey: .sourceAccountId)
        destination = try container.decode(PayoutDestinationResponse.self, forKey: .destination)
        purpose = try container.decodeIfPresent(String.self, forKey: .purpose)
        status = try container.decode(String.self, forKey: .status)
        provider = try container.decodeIfPresent(String.self, forKey: .provider)
        providerRef = try container.decodeIfPresent([String: AnyCodable].self, forKey: .providerRef)
        providerMessage = try container.decodeIfPresent(String.self, forKey: .providerMessage)
        metadata = try container.decodeIfPresent([String: AnyCodable].self, forKey: .metadata)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        updatedAt = try container.decode(String.self, forKey: .updatedAt)
        postedAt = try container.decodeIfPresent(String.self, forKey: .postedAt)
        completedAt = try container.decodeIfPresent(String.self, forKey: .completedAt)
        failedAt = try container.decodeIfPresent(String.self, forKey: .failedAt)
        failureCode = try container.decodeIfPresent(String.self, forKey: .failureCode)
        failureMessage = try container.decodeIfPresent(String.self, forKey: .failureMessage)
        livemode = try container.decode(Bool.self, forKey: .livemode)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("reference_id")
        nonAdditionalPropertyKeys.insert("channel")
        nonAdditionalPropertyKeys.insert("amount")
        nonAdditionalPropertyKeys.insert("magpie_fee")
        nonAdditionalPropertyKeys.insert("source_account_id")
        nonAdditionalPropertyKeys.insert("destination")
        nonAdditionalPropertyKeys.insert("purpose")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("provider")
        nonAdditionalPropertyKeys.insert("provider_ref")
        nonAdditionalPropertyKeys.insert("provider_message")
        nonAdditionalPropertyKeys.insert("metadata")
        nonAdditionalPropertyKeys.insert("created_at")
        nonAdditionalPropertyKeys.insert("updated_at")
        nonAdditionalPropertyKeys.insert("posted_at")
        nonAdditionalPropertyKeys.insert("completed_at")
        nonAdditionalPropertyKeys.insert("failed_at")
        nonAdditionalPropertyKeys.insert("failure_code")
        nonAdditionalPropertyKeys.insert("failure_message")
        nonAdditionalPropertyKeys.insert("livemode")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PayoutResponse: Identifiable {}
