//
// PayoutCollectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PayoutCollectionResponse: Codable, JSONEncodable, Hashable {

    public var data: [PayoutResponse]
    public var limit: Int
    public var nextCursor: String

    public init(data: [PayoutResponse], limit: Int, nextCursor: String) {
        self.data = data
        self.limit = limit
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case limit
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(limit, forKey: .limit)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}

