//
// PayoutDestinationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PayoutDestinationResponse: Codable, JSONEncodable, Hashable {

    public var firstName: String?
    public var lastName: String?
    public var bankCode: String?
    public var accountNumber: String?

    public init(firstName: String? = nil, lastName: String? = nil, bankCode: String? = nil, accountNumber: String? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.bankCode = bankCode
        self.accountNumber = accountNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case bankCode = "bank_code"
        case accountNumber = "account_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(bankCode, forKey: .bankCode)
        try container.encodeIfPresent(accountNumber, forKey: .accountNumber)
    }
}

