/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CanonicalCreateQRReq

class CanonicalCreateQRReqTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CanonicalCreateQRReq
        //val modelInstance = CanonicalCreateQRReq()

        // to test the property `referenceId` - Client-provided identifier used to correlate the QRPh request.
        should("test referenceId") {
            // uncomment below to test the property
            //modelInstance.referenceId shouldBe ("TODO")
        }

        // to test the property `type` - QR type, dynamic for fixed payments or static for amount-less flows.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `submerchantId`
        should("test submerchantId") {
            // uncomment below to test the property
            //modelInstance.submerchantId shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
