/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PayoutResponse
import org.openapitools.client.models.PayoutDestinationResponse

class PayoutResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayoutResponse
        //val modelInstance = PayoutResponse()

        // to test the property `id` - Unique payout identifier.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `referenceId` - Client-provided reference tying to the payout request.
        should("test referenceId") {
            // uncomment below to test the property
            //modelInstance.referenceId shouldBe ("TODO")
        }

        // to test the property `channel` - Payment channel (instapay/pesonet).
        should("test channel") {
            // uncomment below to test the property
            //modelInstance.channel shouldBe ("TODO")
        }

        // to test the property `amount` - Amount in centavos.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `sourceAccountId` - Org bank account used as source.
        should("test sourceAccountId") {
            // uncomment below to test the property
            //modelInstance.sourceAccountId shouldBe ("TODO")
        }

        // to test the property `destination` - Destination bank account data.
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `status` - Current status of the payout.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `createdAt` - ISO timestamp when payout was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - ISO timestamp when the payout was last modified.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `livemode` - True when the payout was created in live mode.
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property `magpieFee`
        should("test magpieFee") {
            // uncomment below to test the property
            //modelInstance.magpieFee shouldBe ("TODO")
        }

        // to test the property `purpose`
        should("test purpose") {
            // uncomment below to test the property
            //modelInstance.purpose shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `providerRef` - Provider-specific reference data.
        should("test providerRef") {
            // uncomment below to test the property
            //modelInstance.providerRef shouldBe ("TODO")
        }

        // to test the property `providerMessage`
        should("test providerMessage") {
            // uncomment below to test the property
            //modelInstance.providerMessage shouldBe ("TODO")
        }

        // to test the property `metadata` - Merchant-defined metadata.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `postedAt`
        should("test postedAt") {
            // uncomment below to test the property
            //modelInstance.postedAt shouldBe ("TODO")
        }

        // to test the property `completedAt`
        should("test completedAt") {
            // uncomment below to test the property
            //modelInstance.completedAt shouldBe ("TODO")
        }

        // to test the property `failedAt`
        should("test failedAt") {
            // uncomment below to test the property
            //modelInstance.failedAt shouldBe ("TODO")
        }

        // to test the property `failureCode`
        should("test failureCode") {
            // uncomment below to test the property
            //modelInstance.failureCode shouldBe ("TODO")
        }

        // to test the property `failureMessage`
        should("test failureMessage") {
            // uncomment below to test the property
            //modelInstance.failureMessage shouldBe ("TODO")
        }

    }
}
