/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.QRPhResponse

class QRPhResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QRPhResponse
        //val modelInstance = QRPhResponse()

        // to test the property `id` - Unique identifier for the QRPh request.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `referenceId` - Client-provided reference for correlating the request.
        should("test referenceId") {
            // uncomment below to test the property
            //modelInstance.referenceId shouldBe ("TODO")
        }

        // to test the property `type` - QR code type, either static or dynamic.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `status` - Current status of the QRPh request.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `createdAt` - ISO timestamp when the QRPh request was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - ISO timestamp when the QRPh request was last updated.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `livemode` - Indicates whether the request was created in live or test mode.
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `submerchantId`
        should("test submerchantId") {
            // uncomment below to test the property
            //modelInstance.submerchantId shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `qrphPayload`
        should("test qrphPayload") {
            // uncomment below to test the property
            //modelInstance.qrphPayload shouldBe ("TODO")
        }

        // to test the property `qrphImage`
        should("test qrphImage") {
            // uncomment below to test the property
            //modelInstance.qrphImage shouldBe ("TODO")
        }

        // to test the property `checkoutUrl`
        should("test checkoutUrl") {
            // uncomment below to test the property
            //modelInstance.checkoutUrl shouldBe ("TODO")
        }

        // to test the property `paymentId`
        should("test paymentId") {
            // uncomment below to test the property
            //modelInstance.paymentId shouldBe ("TODO")
        }

        // to test the property `paidAt`
        should("test paidAt") {
            // uncomment below to test the property
            //modelInstance.paidAt shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `cancelledAt`
        should("test cancelledAt") {
            // uncomment below to test the property
            //modelInstance.cancelledAt shouldBe ("TODO")
        }

        // to test the property `cancellationReason`
        should("test cancellationReason") {
            // uncomment below to test the property
            //modelInstance.cancellationReason shouldBe ("TODO")
        }

    }
}
